In [ ]:
from google.colab import files

uploaded = files.upload()

Saving train.csv to train.csv

In [ ]:
import pandas as pd
df = pd.read_csv("train.csv")
df.shape
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08-11-2017,11-11-2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08-11-2017,11-11-2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12-06-2017,16-06-2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11-10-2016,18-10-2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11-10-2016,18-10-2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9800 non-null   int64
 1   Order ID       9800 non-null   object
 2   Order Date     9800 non-null   object
 3   Ship Date      9800 non-null   object
 4   Ship Mode      9800 non-null   object
 5   Customer ID    9800 non-null   object
 6   Customer Name  9800 non-null   object
 7   Segment        9800 non-null   object
 8   Country        9800 non-null   object
 9   City           9800 non-null   object
 10  State          9800 non-null   object
 11  Postal Code    9789 non-null   float64
 12  Region         9800 non-null   object
 13  Product ID     9800 non-null   object
 14  Category       9800 non-null   object
 15  Sub-Category   9800 non-null   object
 16  Product Name   9800 non-null   object
 17  Sales          9800 non-null   float64
dtypes: float64(2), int64(1), object(15)
memory usage: 1.3+ MB

In [ ]:
import pandas as pd
df=pd.read_csv("train.csv")
df.info()

FileNotFoundError: [Errno 2] No such file or directory: 'train.csv'

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving train.csv to train.csv

In [ ]:
import pandas as pd
df = pd.read_csv("train.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9800 non-null   int64
 1   Order ID       9800 non-null   object
 2   Order Date     9800 non-null   object
 3   Ship Date      9800 non-null   object
 4   Ship Mode      9800 non-null   object
 5   Customer ID    9800 non-null   object
 6   Customer Name  9800 non-null   object
 7   Segment        9800 non-null   object
 8   Country        9800 non-null   object
 9   City           9800 non-null   object
 10  State          9800 non-null   object
 11  Postal Code    9789 non-null   float64
 12  Region         9800 non-null   object
 13  Product ID     9800 non-null   object
 14  Category       9800 non-null   object
 15  Sub-Category   9800 non-null   object
 16  Product Name   9800 non-null   object
 17  Sales          9800 non-null   float64
dtypes: float64(2), int64(1), object(15)
memory usage: 1.3+ MB

In [ ]:
df["Order Date"].head(10)

0    08-11-2017
1    08-11-2017
2    12-06-2017
3    11-10-2016
4    11-10-2016
5    09-06-2015
6    09-06-2015
7    09-06-2015
8    09-06-2015
9    09-06-2015
Name: Order Date, dtype: object

In [ ]:
df['Order Date'].tail(10)

9790    27-03-2018
9791    21-05-2015
9792    21-05-2015
9793    21-05-2015
9794    21-05-2015
9795    21-05-2017
9796    12-01-2016
9797    12-01-2016
9798    12-01-2016
9799    12-01-2016
Name: Order Date, dtype: object

In [ ]:
df['Order Date'].min()

'01-01-2018'

In [ ]:
df['Order Date'].max()

'31-12-2017'

In [ ]:
order_dates = pd.to_datetime(
    df["Order Date"],
    format="%d-%m-%Y",
    errors="coerce"
)

print("Invalid dates:", order_dates.isna().sum())

Invalid dates: 0

In [ ]:
df['Order Date']=order_dates
df['Order Date'].dtype

dtype('<M8[ns]')

In [ ]:
print("Minimum date:", df["Order Date"].min())

Minimum date: 2015-01-03 00:00:00

In [ ]:
print('Maximum date:',df['Order Date'].max())

Maximum date: 2018-12-30 00:00:00

In [ ]:
ship_dates=pd.to_datetime(df['Ship Date'],format='%d-%m-%Y',errors='coerce')
print('Invalid dates:',ship_dates.isna().sum())

Invalid dates: 0

In [ ]:
print("Minimum ship date:", ship_dates.min())
print("Maximum ship date:", ship_dates.max())

Minimum ship date: 2015-01-07 00:00:00
Maximum ship date: 2019-01-05 00:00:00

In [ ]:
df['Ship Date']=ship_dates
df['Order Date']=order_dates
invalid_shipments=df['Ship Date']<df['Order Date']
print('Invalid shipments:',invalid_shipments.sum())

Invalid shipments: 0

In [ ]:
df['Order ID'].duplicated().sum()

np.int64(4878)

In [ ]:
df["Order ID"].value_counts().head(10)

Order ID
CA-2018-100111    14
CA-2018-157987    12
US-2017-108504    11
CA-2017-165330    11
US-2016-126977    10
CA-2016-131338    10
CA-2017-105732    10
CA-2016-104346     9
CA-2016-158421     9
CA-2018-140949     9
Name: count, dtype: int64

In [ ]:
duplicate_order_lines = df.duplicated(
    subset=["Order ID", "Product ID"]
)

print("Duplicate Order ID + Product ID:", duplicate_order_lines.sum())

Duplicate Order ID + Product ID: 8

In [ ]:
df[df.duplicated(
    subset=["Order ID", "Product ID"],
    keep=False
)].sort_values(["Order ID", "Product ID"])

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
6498,6499,CA-2016-103135,2016-07-24,2016-07-28,Standard Class,SS-20515,Shirley Schmidt,Home Office,United States,Louisville,Kentucky,40214.0,South,OFF-BI-10000069,Office Supplies,Binders,"GBC Prepunched Paper, 19-Hole, for Binding Sys...",135.090
6500,6501,CA-2016-103135,2016-07-24,2016-07-28,Standard Class,SS-20515,Shirley Schmidt,Home Office,United States,Louisville,Kentucky,40214.0,South,OFF-BI-10000069,Office Supplies,Binders,"GBC Prepunched Paper, 19-Hole, for Binding Sys...",90.060
350,351,CA-2017-129714,2017-09-01,2017-09-03,First Class,AB-10060,Adam Bellavance,Home Office,United States,New York City,New York,10009.0,East,OFF-PA-10001970,Office Supplies,Paper,Xerox 1881,24.560
352,353,CA-2017-129714,2017-09-01,2017-09-03,First Class,AB-10060,Adam Bellavance,Home Office,United States,New York City,New York,10009.0,East,OFF-PA-10001970,Office Supplies,Paper,Xerox 1881,49.120
1300,1301,CA-2017-137043,2017-12-23,2017-12-25,Second Class,LC-17140,Logan Currie,Consumer,United States,Springfield,Virginia,22153.0,South,FUR-FU-10003664,Furniture,Furnishings,"Electrix Architect's Clamp-On Swing Arm Lamp, ...",572.760
1301,1302,CA-2017-137043,2017-12-23,2017-12-25,Second Class,LC-17140,Logan Currie,Consumer,United States,Springfield,Virginia,22153.0,South,FUR-FU-10003664,Furniture,Furnishings,"Electrix Architect's Clamp-On Swing Arm Lamp, ...",286.380
9168,9169,CA-2017-140571,2017-03-15,2017-03-19,Standard Class,SJ-20125,Sanjit Jacobs,Home Office,United States,Jackson,Mississippi,39212.0,South,OFF-PA-10001954,Office Supplies,Paper,Xerox 1964,319.760
9169,9170,CA-2017-140571,2017-03-15,2017-03-19,Standard Class,SJ-20125,Sanjit Jacobs,Home Office,United States,Jackson,Mississippi,39212.0,South,OFF-PA-10001954,Office Supplies,Paper,Xerox 1964,45.680
7881,7882,CA-2018-118017,2018-12-03,2018-12-06,Second Class,LC-16870,Lena Cacioppo,Consumer,United States,Thornton,Colorado,80229.0,West,TEC-AC-10002006,Technology,Accessories,Memorex Micro Travel Drive 16 GB,76.752
7882,7883,CA-2018-118017,2018-12-03,2018-12-06,Second Class,LC-16870,Lena Cacioppo,Consumer,United States,Thornton,Colorado,80229.0,West,TEC-AC-10002006,Technology,Accessories,Memorex Micro Travel Drive 16 GB,102.336
3183,3184,CA-2018-152912,2018-11-09,2018-11-12,Second Class,BM-11650,Brian Moss,Corporate,United States,Columbia,Maryland,21044.0,East,OFF-ST-10003208,Office Supplies,Storage,Adjustable Depth Letter/Legal Cart,1633.140
3184,3185,CA-2018-152912,2018-11-09,2018-11-12,Second Class,BM-11650,Brian Moss,Corporate,United States,Columbia,Maryland,21044.0,East,OFF-ST-10003208,Office Supplies,Storage,Adjustable Depth Letter/Legal Cart,544.380
3405,3406,US-2015-150119,2015-04-23,2015-04-27,Standard Class,LB-16795,Laurel Beltran,Home Office,United States,Columbus,Ohio,43229.0,East,FUR-CH-10002965,Furniture,Chairs,Global Leather Highback Executive Chair with P...,281.372
3406,3407,US-2015-150119,2015-04-23,2015-04-27,Standard Class,LB-16795,Laurel Beltran,Home Office,United States,Columbus,Ohio,43229.0,East,FUR-CH-10002965,Furniture,Chairs,Global Leather Highback Executive Chair with P...,281.372
430,431,US-2017-123750,2017-04-15,2017-04-21,Standard Class,RB-19795,Ross Baird,Home Office,United States,Gastonia,North Carolina,28052.0,South,TEC-AC-10004659,Technology,Accessories,Imation Secure+ Hardware Encrypted USB 2.0 Fla...,408.744
431,432,US-2017-123750,2017-04-15,2017-04-21,Standard Class,RB-19795,Ross Baird,Home Office,United States,Gastonia,North Carolina,28052.0,South,TEC-AC-10004659,Technology,Accessories,Imation Secure+ Hardware Encrypted USB 2.0 Fla...,291.960

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving train.csv to train.csv

In [ ]:
import pandas as pd
df = pd.read_csv("train.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9800 non-null   int64
 1   Order ID       9800 non-null   object
 2   Order Date     9800 non-null   object
 3   Ship Date      9800 non-null   object
 4   Ship Mode      9800 non-null   object
 5   Customer ID    9800 non-null   object
 6   Customer Name  9800 non-null   object
 7   Segment        9800 non-null   object
 8   Country        9800 non-null   object
 9   City           9800 non-null   object
 10  State          9800 non-null   object
 11  Postal Code    9789 non-null   float64
 12  Region         9800 non-null   object
 13  Product ID     9800 non-null   object
 14  Category       9800 non-null   object
 15  Sub-Category   9800 non-null   object
 16  Product Name   9800 non-null   object
 17  Sales          9800 non-null   float64
dtypes: float64(2), int64(1), object(15)
memory usage: 1.3+ MB

In [ ]:
missing = df.isna().sum()

print(missing[missing > 0])

Postal Code    11
dtype: int64

In [ ]:
missing_postal=df[df['Postal Code'].isna()]
missing_postal.head(12)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
2234,2235,CA-2018-104066,05-12-2018,10-12-2018,Standard Class,QJ-19255,Quincy Jones,Corporate,United States,Burlington,Vermont,NaN,East,TEC-AC-10001013,Technology,Accessories,Logitech ClearChat Comfort/USB Headset H390,205.03
5274,5275,CA-2016-162887,07-11-2016,09-11-2016,Second Class,SV-20785,Stewart Visinsky,Consumer,United States,Burlington,Vermont,NaN,East,FUR-CH-10000595,Furniture,Chairs,Safco Contoured Stacking Chairs,715.20
8798,8799,US-2017-150140,06-04-2017,10-04-2017,Standard Class,VM-21685,Valerie Mitchum,Home Office,United States,Burlington,Vermont,NaN,East,TEC-PH-10002555,Technology,Phones,Nortel Meridian M5316 Digital phone,1294.75
9146,9147,US-2017-165505,23-01-2017,27-01-2017,Standard Class,CB-12535,Claudia Bergmann,Corporate,United States,Burlington,Vermont,NaN,East,TEC-AC-10002926,Technology,Accessories,Logitech Wireless Marathon Mouse M705,99.98
9147,9148,US-2017-165505,23-01-2017,27-01-2017,Standard Class,CB-12535,Claudia Bergmann,Corporate,United States,Burlington,Vermont,NaN,East,OFF-AR-10003477,Office Supplies,Art,4009 Highlighters,8.04
9148,9149,US-2017-165505,23-01-2017,27-01-2017,Standard Class,CB-12535,Claudia Bergmann,Corporate,United States,Burlington,Vermont,NaN,East,OFF-ST-10001526,Office Supplies,Storage,Iceberg Mobile Mega Data/Printer Cart,1564.29
9386,9387,US-2018-127292,19-01-2018,23-01-2018,Standard Class,RM-19375,Raymond Messe,Consumer,United States,Burlington,Vermont,NaN,East,OFF-PA-10000157,Office Supplies,Paper,Xerox 191,79.92
9387,9388,US-2018-127292,19-01-2018,23-01-2018,Standard Class,RM-19375,Raymond Messe,Consumer,United States,Burlington,Vermont,NaN,East,OFF-PA-10001970,Office Supplies,Paper,Xerox 1881,12.28
9388,9389,US-2018-127292,19-01-2018,23-01-2018,Standard Class,RM-19375,Raymond Messe,Consumer,United States,Burlington,Vermont,NaN,East,OFF-AP-10000828,Office Supplies,Appliances,Avanti 4.4 Cu. Ft. Refrigerator,542.94
9389,9390,US-2018-127292,19-01-2018,23-01-2018,Standard Class,RM-19375,Raymond Messe,Consumer,United States,Burlington,Vermont,NaN,East,OFF-EN-10001509,Office Supplies,Envelopes,Poly String Tie Envelopes,2.04
9741,9742,CA-2016-117086,08-11-2016,12-11-2016,Standard Class,QJ-19255,Quincy Jones,Corporate,United States,Burlington,Vermont,NaN,East,FUR-BO-10004834,Furniture,Bookcases,"Riverside Palais Royal Lawyers Bookcase, Royal...",4404.90

In [ ]:
df[df['City']=='Burlington']['Postal Code']

683     27217.0
684     27217.0
1008    52601.0
1038    27217.0
1039    27217.0
1393    27217.0
2234        NaN
2928    27217.0
5065    27217.0
5066    27217.0
5274        NaN
8317    27217.0
8318    27217.0
8410    27217.0
8798        NaN
9146        NaN
9147        NaN
9148        NaN
9209    52601.0
9210    52601.0
9386        NaN
9387        NaN
9388        NaN
9389        NaN
9741        NaN
Name: Postal Code, dtype: float64

In [ ]:
df[df["City"] == "Burlington"][["State", "Postal Code"]]

               State  Postal Code
683   North Carolina      27217.0
684   North Carolina      27217.0
1008            Iowa      52601.0
1038  North Carolina      27217.0
1039  North Carolina      27217.0
1393  North Carolina      27217.0
2234         Vermont          NaN
2928  North Carolina      27217.0
5065  North Carolina      27217.0
5066  North Carolina      27217.0
5274         Vermont          NaN
8317  North Carolina      27217.0
8318  North Carolina      27217.0
8410  North Carolina      27217.0
8798         Vermont          NaN
9146         Vermont          NaN
9147         Vermont          NaN
9148         Vermont          NaN
9209            Iowa      52601.0
9210            Iowa      52601.0
9386         Vermont          NaN
9387         Vermont          NaN
9388         Vermont          NaN
9389         Vermont          NaN
9741         Vermont          NaN

In [ ]:
missing_count = df["Postal Code"].isna().sum()
total_count = len(df)

print("Missing:", missing_count)
print("Total:", total_count)
print("Missing %:", (missing_count / total_count) * 100)

Missing: 11
Total: 9800
Missing %: 0.11224489795918367

In [ ]:
df["Ship Mode"].unique()

array(['Second Class', 'Standard Class', 'First Class', 'Same Day'],
      dtype=object)

In [ ]:
df["Ship Mode"].value_counts()

Ship Mode
Standard Class    5859
Second Class      1902
First Class       1501
Same Day           538
Name: count, dtype: int64

In [ ]:
total_ship_mode=df["Ship Mode"].value_counts().sum()
print(total_ship_mode)

9800

In [ ]:
df['Segment'].unique()

array(['Consumer', 'Corporate', 'Home Office'], dtype=object)

In [ ]:
df["Segment"].value_counts()

Segment
Consumer       5101
Corporate      2953
Home Office    1746
Name: count, dtype: int64

In [ ]:
total_segment=df['Segment'].value_counts().sum()
print(total_segment)

9800

In [ ]:
df["Country"].unique()

array(['United States'], dtype=object)

In [ ]:
df["City"].unique()

array(['Henderson', 'Los Angeles', 'Fort Lauderdale', 'Concord',
       'Seattle', 'Fort Worth', 'Madison', 'West Jordan', 'San Francisco',
       'Fremont', 'Philadelphia', 'Orem', 'Houston', 'Richardson',
       'Naperville', 'Melbourne', 'Eagan', 'Westland', 'Dover',
       'New Albany', 'New York City', 'Troy', 'Chicago', 'Gilbert',
       'Springfield', 'Jackson', 'Memphis', 'Decatur', 'Durham',
       'Columbia', 'Rochester', 'Minneapolis', 'Portland', 'Saint Paul',
       'Aurora', 'Charlotte', 'Orland Park', 'Urbandale', 'Columbus',
       'Bristol', 'Wilmington', 'Bloomington', 'Phoenix', 'Roseville',
       'Independence', 'Pasadena', 'Newark', 'Franklin', 'Scottsdale',
       'San Jose', 'Edmond', 'Carlsbad', 'San Antonio', 'Monroe',
       'Fairfield', 'Grand Prairie', 'Redlands', 'Hamilton', 'Westfield',
       'Akron', 'Denver', 'Dallas', 'Whittier', 'Saginaw', 'Medina',
       'Dublin', 'Detroit', 'Tampa', 'Santa Clara', 'Lakeville',
       'San Diego', 'Brentwood', 'Chapel Hill', 'Morristown',
       'Cincinnati', 'Inglewood', 'Tamarac', 'Colorado Springs',
       'Belleville', 'Taylor', 'Lakewood', 'Arlington', 'Arvada',
       'Hackensack', 'Saint Petersburg', 'Long Beach', 'Hesperia',
       'Murfreesboro', 'Layton', 'Austin', 'Lowell', 'Manchester',
       'Harlingen', 'Tucson', 'Quincy', 'Pembroke Pines', 'Des Moines',
       'Peoria', 'Las Vegas', 'Warwick', 'Miami', 'Huntington Beach',
       'Richmond', 'Louisville', 'Lawrence', 'Canton', 'New Rochelle',
       'Gastonia', 'Jacksonville', 'Auburn', 'Norman', 'Park Ridge',
       'Amarillo', 'Lindenhurst', 'Huntsville', 'Fayetteville',
       'Costa Mesa', 'Parker', 'Atlanta', 'Gladstone', 'Great Falls',
       'Lakeland', 'Montgomery', 'Mesa', 'Green Bay', 'Anaheim',
       'Marysville', 'Salem', 'Laredo', 'Grove City', 'Dearborn',
       'Warner Robins', 'Vallejo', 'Mission Viejo', 'Rochester Hills',
       'Plainfield', 'Sierra Vista', 'Vancouver', 'Cleveland', 'Tyler',
       'Burlington', 'Waynesboro', 'Chester', 'Cary', 'Palm Coast',
       'Mount Vernon', 'Hialeah', 'Oceanside', 'Evanston', 'Trenton',
       'Cottage Grove', 'Bossier City', 'Lancaster', 'Asheville',
       'Lake Elsinore', 'Omaha', 'Edmonds', 'Santa Ana', 'Milwaukee',
       'Florence', 'Lorain', 'Linden', 'Salinas', 'New Brunswick',
       'Garland', 'Norwich', 'Alexandria', 'Toledo', 'Farmington',
       'Riverside', 'Torrance', 'Round Rock', 'Boca Raton',
       'Virginia Beach', 'Murrieta', 'Olympia', 'Washington',
       'Jefferson City', 'Saint Peters', 'Rockford', 'Brownsville',
       'Yonkers', 'Oakland', 'Clinton', 'Encinitas', 'Roswell',
       'Jonesboro', 'Antioch', 'Homestead', 'La Porte', 'Lansing',
       'Cuyahoga Falls', 'Reno', 'Harrisonburg', 'Escondido', 'Royal Oak',
       'Rockville', 'Coral Springs', 'Buffalo', 'Boynton Beach',
       'Gulfport', 'Fresno', 'Greenville', 'Macon', 'Cedar Rapids',
       'Providence', 'Pueblo', 'Deltona', 'Murray', 'Middletown',
       'Freeport', 'Pico Rivera', 'Provo', 'Pleasant Grove', 'Smyrna',
       'Parma', 'Mobile', 'New Bedford', 'Irving', 'Vineland', 'Glendale',
       'Niagara Falls', 'Thomasville', 'Westminster', 'Coppell', 'Pomona',
       'North Las Vegas', 'Allentown', 'Tempe', 'Laguna Niguel',
       'Bridgeton', 'Everett', 'Watertown', 'Appleton', 'Bellevue',
       'Allen', 'El Paso', 'Grapevine', 'Carrollton', 'Kent', 'Lafayette',
       'Tigard', 'Skokie', 'Plano', 'Suffolk', 'Indianapolis', 'Bayonne',
       'Greensboro', 'Baltimore', 'Kenosha', 'Olathe', 'Tulsa', 'Redmond',
       'Raleigh', 'Muskogee', 'Meriden', 'Bowling Green', 'South Bend',
       'Spokane', 'Keller', 'Port Orange', 'Medford', 'Charlottesville',
       'Missoula', 'Apopka', 'Reading', 'Broomfield', 'Paterson',
       'Oklahoma City', 'Chesapeake', 'Lubbock', 'Johnson City',
       'San Bernardino', 'Leominster', 'Bozeman', 'Perth Amboy',
       'Ontario', 'Rancho Cucamonga', 'Moorhead', 'Mesquite', 'Stockton',
       'Ormond Beach', 'Sunnyvale', 'York', 'College Station',
       'Saint Louis', 'Manteca', 'San Angelo', 'Salt Lake City',
       'Knoxville', 'Little Rock', 'Lincoln Park', 'Marion', 'Littleton',
       'Bangor', 'Southaven', 'New Castle', 'Midland', 'Sioux Falls',
       'Fort Collins', 'Clarksville', 'Sacramento', 'Thousand Oaks',
       'Malden', 'Holyoke', 'Albuquerque', 'Sparks', 'Coachella',
       'Elmhurst', 'Passaic', 'North Charleston', 'Newport News',
       'Jamestown', 'Mishawaka', 'La Quinta', 'Tallahassee', 'Nashville',
       'Bellingham', 'Woodstock', 'Haltom City', 'Wheeling',
       'Summerville', 'Hot Springs', 'Englewood', 'Las Cruces', 'Hoover',
       'Frisco', 'Vacaville', 'Waukesha', 'Bakersfield', 'Pompano Beach',
       'Corpus Christi', 'Redondo Beach', 'Orlando', 'Orange',
       'Lake Charles', 'Highland Park', 'Hempstead', 'Noblesville',
       'Apple Valley', 'Mount Pleasant', 'Sterling Heights', 'Eau Claire',
       'Pharr', 'Billings', 'Gresham', 'Chattanooga', 'Meridian',
       'Bolingbrook', 'Maple Grove', 'Woodland', 'Missouri City',
       'Pearland', 'San Mateo', 'Grand Rapids', 'Visalia',
       'Overland Park', 'Temecula', 'Yucaipa', 'Revere', 'Conroe',
       'Tinley Park', 'Dubuque', 'Dearborn Heights', 'Santa Fe',
       'Hickory', 'Carol Stream', 'Saint Cloud', 'North Miami',
       'Plantation', 'Port Saint Lucie', 'Rock Hill', 'Odessa',
       'West Allis', 'Chula Vista', 'Manhattan', 'Altoona', 'Thornton',
       'Champaign', 'Texarkana', 'Edinburg', 'Baytown', 'Greenwood',
       'Woonsocket', 'Superior', 'Bedford', 'Covington', 'Broken Arrow',
       'Miramar', 'Hollywood', 'Deer Park', 'Wichita', 'Mcallen',
       'Iowa City', 'Boise', 'Cranston', 'Port Arthur', 'Citrus Heights',
       'The Colony', 'Daytona Beach', 'Bullhead City', 'Portage', 'Fargo',
       'Elkhart', 'San Gabriel', 'Margate', 'Sandy Springs', 'Mentor',
       'Lawton', 'Hampton', 'Rome', 'La Crosse', 'Lewiston',
       'Hattiesburg', 'Danville', 'Logan', 'Waterbury', 'Athens',
       'Avondale', 'Marietta', 'Yuma', 'Wausau', 'Pasco', 'Oak Park',
       'Pensacola', 'League City', 'Gaithersburg', 'Lehi', 'Tuscaloosa',
       'Moreno Valley', 'Georgetown', 'Loveland', 'Chandler', 'Helena',
       'Kirkwood', 'Waco', 'Frankfort', 'Bethlehem', 'Grand Island',
       'Woodbury', 'Rogers', 'Clovis', 'Jupiter', 'Santa Barbara',
       'Cedar Hill', 'Norfolk', 'Draper', 'Ann Arbor', 'La Mesa',
       'Pocatello', 'Holland', 'Milford', 'Buffalo Grove', 'Lake Forest',
       'Redding', 'Chico', 'Utica', 'Conway', 'Cheyenne', 'Owensboro',
       'Caldwell', 'Kenner', 'Nashua', 'Bartlett', 'Redwood City',
       'Lebanon', 'Santa Maria', 'Des Plaines', 'Longview',
       'Hendersonville', 'Waterloo', 'Cambridge', 'Palatine', 'Beverly',
       'Eugene', 'Oxnard', 'Renton', 'Glenview', 'Delray Beach',
       'Commerce City', 'Texas City', 'Wilson', 'Rio Rancho', 'Goldsboro',
       'Montebello', 'El Cajon', 'Beaumont', 'West Palm Beach', 'Abilene',
       'Normal', 'Saint Charles', 'Camarillo', 'Hillsboro', 'Burbank',
       'Modesto', 'Garden City', 'Atlantic City', 'Longmont', 'Davis',
       'Morgan Hill', 'Clifton', 'Sheboygan', 'East Point', 'Rapid City',
       'Andover', 'Kissimmee', 'Shelton', 'Danbury', 'Sanford',
       'San Marcos', 'Greeley', 'Mansfield', 'Elyria', 'Twin Falls',
       'Coral Gables', 'Romeoville', 'Marlborough', 'Laurel', 'Bryan',
       'Pine Bluff', 'Aberdeen', 'Hagerstown', 'East Orange',
       'Arlington Heights', 'Oswego', 'Coon Rapids', 'San Clemente',
       'San Luis Obispo', 'Springdale'], dtype=object)

In [ ]:
df["City"].value_counts().head(10)

City
New York City    891
Los Angeles      728
Philadelphia     532
San Francisco    500
Seattle          426
Houston          374
Chicago          308
Columbus         221
San Diego        170
Springfield      161
Name: count, dtype: int64

In [ ]:
total_city_count=df["City"].value_counts().head(10).sum()
print(total_city_count)

4311

In [ ]:
df["City"].isna().sum()

np.int64(0)

In [ ]:
df["State"].unique()

array(['Kentucky', 'California', 'Florida', 'North Carolina',
       'Washington', 'Texas', 'Wisconsin', 'Utah', 'Nebraska',
       'Pennsylvania', 'Illinois', 'Minnesota', 'Michigan', 'Delaware',
       'Indiana', 'New York', 'Arizona', 'Virginia', 'Tennessee',
       'Alabama', 'South Carolina', 'Oregon', 'Colorado', 'Iowa', 'Ohio',
       'Missouri', 'Oklahoma', 'New Mexico', 'Louisiana', 'Connecticut',
       'New Jersey', 'Massachusetts', 'Georgia', 'Nevada', 'Rhode Island',
       'Mississippi', 'Arkansas', 'Montana', 'New Hampshire', 'Maryland',
       'District of Columbia', 'Kansas', 'Vermont', 'Maine',
       'South Dakota', 'Idaho', 'North Dakota', 'Wyoming',
       'West Virginia'], dtype=object)

In [ ]:
df["State"].value_counts().head(10)

State
California        1946
New York          1097
Texas              973
Pennsylvania       582
Washington         504
Illinois           483
Ohio               454
Florida            373
Michigan           253
North Carolina     247
Name: count, dtype: int64

In [ ]:
df["State"].isna().sum()

np.int64(0)

In [ ]:
city_state=df.groupby('City')['State'].nunique()
print(city_state[city_state>1])

City
Apple Valley      2
Arlington         2
Auburn            3
Aurora            2
Bloomington       2
Bowling Green     2
Bristol           2
Burlington        3
Columbia          4
Columbus          3
Concord           3
Danville          2
Decatur           2
Des Moines        2
Dover             2
Dublin            2
Everett           2
Fairfield         3
Fayetteville      2
Florence          3
Franklin          3
Freeport          2
Henderson         2
Huntsville        2
Jackson           3
Jacksonville      2
Kent              2
Lafayette         2
Lakewood          3
Lancaster         3
Lawrence          2
Lewiston          2
Long Beach        2
Louisville        2
Marion            2
Monroe            2
Mount Pleasant    2
Murray            2
Newark            2
Oak Park          2
Oceanside         2
Pasadena          2
Peoria            2
Quincy            2
Redmond           2
Richmond          3
Rochester         2
Roseville         3
Saint Charles     2
Salem             2
Smyrna            2
Springfield       4
Troy              2
Wheeling          2
Wilmington        2
Name: State, dtype: int64

In [ ]:
city_state_count = df.groupby(["City", "State"]).size()

print(city_state_count[city_state_count > 1].head(20))

City          State
Akron         Ohio              20
Albuquerque   New Mexico        14
Alexandria    Virginia          16
Allen         Texas              4
Allentown     Pennsylvania       7
Altoona       Pennsylvania       2
Amarillo      Texas             10
Anaheim       California        19
Andover       Massachusetts      4
Ann Arbor     Michigan           5
Apopka        Florida            7
Apple Valley  California         7
              Minnesota          2
Appleton      Wisconsin          2
Arlington     Texas             28
              Virginia          32
Arvada        Colorado           4
Asheville     North Carolina     7
Athens        Georgia            6
Atlanta       Georgia           39
dtype: int64

In [ ]:
df[df["Postal Code"].isna()][["City", "State", "Postal Code"]]

            City    State  Postal Code
2234  Burlington  Vermont          NaN
5274  Burlington  Vermont          NaN
8798  Burlington  Vermont          NaN
9146  Burlington  Vermont          NaN
9147  Burlington  Vermont          NaN
9148  Burlington  Vermont          NaN
9386  Burlington  Vermont          NaN
9387  Burlington  Vermont          NaN
9388  Burlington  Vermont          NaN
9389  Burlington  Vermont          NaN
9741  Burlington  Vermont          NaN

In [ ]:
df["Postal Code"].dtype

dtype('float64')

In [ ]:
print("Minimum Postal Code:", df["Postal Code"].min())
print("Maximum Postal Code:", df["Postal Code"].max())

Minimum Postal Code: 1040.0
Maximum Postal Code: 99301.0

In [ ]:
df["Postal Code"].dropna().astype(int).astype(str).str.len().value_counts()

Postal Code
5    9360
4     429
Name: count, dtype: int64

In [ ]:
postal = df["Postal Code"].dropna()
postal = postal.astype(int)
postal = postal.astype(str)

postal_length = postal.str.len()

four_digit = postal[postal_length == 4]

print(four_digit.head(20))

185    6824
197    7090
267    7960
298    7109
299    7109
300    7109
301    7109
302    7109
306    8701
307    8701
313    7601
346    1852
347    1852
348    1852
366    6040
367    6040
368    6040
369    6040
377    2038
395    2886
Name: Postal Code, dtype: object

In [ ]:
df["Postal Code"] = df["Postal Code"].apply(
    lambda x: f"{int(x):05d}" if pd.notna(x) else None
)

In [ ]:
print(df["Postal Code"].head(20))

0     42420
1     42420
2     90036
3     33311
4     33311
5     90032
6     90032
7     90032
8     90032
9     90032
10    90032
11    90032
12    28027
13    98103
14    76106
15    76106
16    53711
17    84084
18    94109
19    94109
Name: Postal Code, dtype: object

In [ ]:
postal_start_zero = df["Postal Code"].dropna()

print(postal_start_zero[postal_start_zero.str.startswith("0")].head(20))

185    06824
197    07090
267    07960
298    07109
299    07109
300    07109
301    07109
302    07109
306    08701
307    08701
313    07601
346    01852
347    01852
348    01852
366    06040
367    06040
368    06040
369    06040
377    02038
395    02886
Name: Postal Code, dtype: object

In [ ]:
df.to_excel("sales_cleaned.xlsx", index=False)

In [ ]:
from google.colab import files

files.download("sales_cleaned.xlsx")

In [ ]:
df["Postal Code"].isna().sum()

np.int64(11)

In [ ]:
df["Postal Code"].dropna().str.len().value_counts()

Postal Code
5    9789
Name: count, dtype: int64

In [ ]:
print(df["Postal Code"].dtype)

object

In [ ]:
df["Sales"].isna().sum()

np.int64(0)

In [ ]:
df["Sales"].lt(0).sum()

np.int64(0)

In [ ]:
(df["Sales"] == 0).sum()

np.int64(0)

In [ ]:
print("Minimum Sales:", df["Sales"].min())
print("Maximum Sales:", df["Sales"].max())

Minimum Sales: 0.444
Maximum Sales: 22638.48

In [ ]:
print("Average Sales:", df["Sales"].mean())
print("Median Sales:", df["Sales"].median())

Average Sales: 230.7690594591837
Median Sales: 54.489999999999995

In [ ]:
df["Sales"].nlargest(10)

2697    22638.480
6826    17499.950
8153    13999.960
2623    11199.968
4190    10499.970
9039     9892.740
4098     9449.950
4277     9099.930
8488     8749.950
6425     8399.976
Name: Sales, dtype: float64

In [ ]:
df["Order ID"].isna().sum()

np.int64(0)

In [ ]:
df["Order ID"].head(10)

0    CA-2017-152156
1    CA-2017-152156
2    CA-2017-138688
3    US-2016-108966
4    US-2016-108966
5    CA-2015-115812
6    CA-2015-115812
7    CA-2015-115812
8    CA-2015-115812
9    CA-2015-115812
Name: Order ID, dtype: object

In [ ]:
df["Order ID"].str.len().value_counts()

Order ID
14    9800
Name: count, dtype: int64

In [ ]:
df["Order ID"].str[:2].value_counts()

Order ID
CA    8161
US    1639
Name: count, dtype: int64

In [ ]:
df["Order ID"].str[3:7].value_counts().sort_index()

Order ID
2015    1953
2016    2055
2017    2534
2018    3258
Name: count, dtype: int64

In [ ]:
order_id_year = df["Order ID"].str[3:7]
order_date_year = df["Order Date"].dt.year.astype(str)

print("Year mismatches:", (order_id_year != order_date_year).sum())

AttributeError: Can only use .dt accessor with datetimelike values

In [ ]:
df["Order Date"].dtype

dtype('O')

In [ ]:
order_dates = pd.to_datetime(
    df["Order Date"],
    format="%d-%m-%Y",
    errors="coerce"
)

In [ ]:
order_dates.dtype

dtype('<M8[ns]')

In [ ]:
df["Order Date"] = order_dates

In [ ]:
df["Order Date"].dtype

dtype('<M8[ns]')

In [ ]:
order_id_year = df["Order ID"].str[3:7]
order_date_year = df["Order Date"].dt.year.astype(str)

print("Year mismatches:", (order_id_year != order_date_year).sum())

Year mismatches: 0

In [ ]:
df["Product ID"].isna().sum()

np.int64(0)

In [ ]:
df["Product ID"].head(10)

0    FUR-BO-10001798
1    FUR-CH-10000454
2    OFF-LA-10000240
3    FUR-TA-10000577
4    OFF-ST-10000760
5    FUR-FU-10001487
6    OFF-AR-10002833
7    TEC-PH-10002275
8    OFF-BI-10003910
9    OFF-AP-10002892
Name: Product ID, dtype: object

In [ ]:
df["Product ID"].str.len().value_counts()

Product ID
15    9800
Name: count, dtype: int64

In [ ]:
df["Product ID"].str[:3].value_counts()

Product ID
OFF    5909
FUR    2078
TEC    1813
Name: count, dtype: int64

In [ ]:
product_prefix = df["Product ID"].str[:3]

category_prefix = df["Category"].map({
    "Office Supplies": "OFF",
    "Furniture": "FUR",
    "Technology": "TEC"
})

print("Category mismatches:", (product_prefix != category_prefix).sum())

Category mismatches: 0

In [ ]:
df["Product ID"].str[4:6].value_counts()

Product ID
BI    1492
PA    1338
FU     931
PH     876
ST     832
AR     785
AC     756
CH     607
AP     459
LA     357
TA     314
EN     248
BO     226
FA     214
SU     184
MA     115
CO      66
Name: count, dtype: int64

In [ ]:
df.groupby(
    df["Product ID"].str[4:6]
)["Sub-Category"].nunique()

Product ID
AC    1
AP    1
AR    1
BI    1
BO    1
CH    1
CO    1
EN    1
FA    1
FU    1
LA    1
MA    1
PA    1
PH    1
ST    1
SU    1
TA    1
Name: Sub-Category, dtype: int64

In [ ]:
import pandas as pd

from google.colab import files
uploaded = files.upload()  # Make sure 'upload' is lowercase

Saving train.csv to train.csv

In [ ]:
import pandas as pd

# Replace 'your_file.csv' with the actual name of your uploaded file
df = pd.read_csv('train.csv')

In [ ]:
# This assigns the mapped values back to the "Category" column
df["Category"] = df["Category"].map({
    "Office Supplies": "OFF",
    "Furniture": "FUR",
    "Technology": "TEC"
})

In [ ]:
print(df["Order Date"].head())
print(df["Order Date"].dtype)

0    08-11-2017
1    08-11-2017
2    12-06-2017
3    11-10-2016
4    11-10-2016
Name: Order Date, dtype: object
object

In [ ]:
df['Order Date']=pd.to_datetime(df['Order Date'],format='%d-%m-%Y',errors='coerce')
print(df['Order Date'].head())
print(df['Order Date'].dtype)

0   2017-11-08
1   2017-11-08
2   2017-06-12
3   2016-10-11
4   2016-10-11
Name: Order Date, dtype: datetime64[ns]
datetime64[ns]

In [ ]:
df['Order Year']=df['Order Date'].dt.year
print(df[['Order Date','Order Year']].head())

  Order Date  Order Year
0 2017-11-08        2017
1 2017-11-08        2017
2 2017-06-12        2017
3 2016-10-11        2016
4 2016-10-11        2016

In [ ]:
print(df['Order Year'].unique())

[2017 2016 2015 2018]

In [ ]:
print(df["Order Year"].isna().sum())

0

In [ ]:
df["Order Month"] = df["Order Date"].dt.month
print(df[['Order Date','Order Month']].head())

  Order Date  Order Month
0 2017-11-08           11
1 2017-11-08           11
2 2017-06-12            6
3 2016-10-11           10
4 2016-10-11           10

In [ ]:
print(df["Order Month"].unique())

[11  6 10  4 12  5  8  7  9  1  3  2]

In [ ]:
print(df["Order Month"].isna().sum())

0

In [ ]:
df['Order Quarter']=df['Order Date'].dt.quarter
print(df[['Order Date','Order Quarter']].head())

  Order Date  Order Quarter
0 2017-11-08              4
1 2017-11-08              4
2 2017-06-12              2
3 2016-10-11              4
4 2016-10-11              4

In [ ]:
print(df["Order Quarter"].unique())

[4 2 3 1]

In [ ]:
print(df["Order Quarter"].isna().sum())

0

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving train.csv to train.csv

In [ ]:
import pandas as pd
df = pd.read_csv("train.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9800 non-null   int64
 1   Order ID       9800 non-null   object
 2   Order Date     9800 non-null   object
 3   Ship Date      9800 non-null   object
 4   Ship Mode      9800 non-null   object
 5   Customer ID    9800 non-null   object
 6   Customer Name  9800 non-null   object
 7   Segment        9800 non-null   object
 8   Country        9800 non-null   object
 9   City           9800 non-null   object
 10  State          9800 non-null   object
 11  Postal Code    9789 non-null   float64
 12  Region         9800 non-null   object
 13  Product ID     9800 non-null   object
 14  Category       9800 non-null   object
 15  Sub-Category   9800 non-null   object
 16  Product Name   9800 non-null   object
 17  Sales          9800 non-null   float64
dtypes: float64(2), int64(1), object(15)
memory usage: 1.3+ MB

In [ ]:
df['ship days']= (df['Ship Date']-df['Order Date']).dt.days

TypeError: unsupported operand type(s) for -: 'str' and 'str'

In [ ]:
print(df["Order Date"].dtype)
print(df["Ship Date"].dtype)

object
object

In [ ]:
df["Order Date"] = pd.to_datetime(
    df["Order Date"],
    format="%d-%m-%Y"
)

df["Ship Date"] = pd.to_datetime(
    df["Ship Date"],
    format="%d-%m-%Y"
)

In [ ]:
print(df["Order Date"].dtype)
print(df["Ship Date"].dtype)

datetime64[ns]
datetime64[ns]

In [ ]:
df['ship days']= (df['Ship Date']-df['Order Date']).dt.days

In [ ]:
print(df[["Order Date", "Ship Date", "Ship Days"]].head())

KeyError: "['Ship Days'] not in index"

In [ ]:
df["Ship Days"] = (
    df["Ship Date"] - df["Order Date"]
).dt.days

In [ ]:
print(df[["Order Date", "Ship Date", "Ship Days"]].head())

  Order Date  Ship Date  Ship Days
0 2017-11-08 2017-11-11          3
1 2017-11-08 2017-11-11          3
2 2017-06-12 2017-06-16          4
3 2016-10-11 2016-10-18          7
4 2016-10-11 2016-10-18          7

In [ ]:
print(df["Ship Days"].isna().sum())

0

In [ ]:
print((df["Ship Days"] < 0).sum())

0

In [ ]:
print(df["Ship Days"].min())
print(df["Ship Days"].max())

0
7

In [ ]:
print(df["Ship Days"].mean())

3.9611224489795918

In [ ]:
print(df["Ship Days"].value_counts().sort_index())

Ship Days
0     514
1     363
2    1295
3     978
4    2718
5    2147
6    1170
7     615
Name: count, dtype: int64

In [ ]:
print(df["Ship Days"].value_counts().sum())

9800

In [ ]:
print(df.groupby("Ship Mode")["Ship Days"].mean())

Ship Mode
First Class       2.179214
Same Day          0.044610
Second Class      3.249211
Standard Class    5.008363
Name: Ship Days, dtype: float64

In [ ]:
print(df["Ship Mode"].value_counts())

Ship Mode
Standard Class    5859
Second Class      1902
First Class       1501
Same Day           538
Name: count, dtype: int64

In [ ]:
print(df.groupby("Ship Mode")['Sales'].sum())

Ship Mode
First Class       3.455723e+05
Same Day          1.252190e+05
Second Class      4.499142e+05
Standard Class    1.340831e+06
Name: Sales, dtype: float64

In [ ]:
print(
    df.groupby("Ship Mode")["Sales"].sum()
    / df["Sales"].sum() * 100
)

Ship Mode
First Class       15.280417
Same Day           5.536900
Second Class      19.894179
Standard Class    59.288503
Name: Sales, dtype: float64

In [ ]:
print(
    df.groupby(["Region", "Ship Mode"])["Sales"].sum()
)

Region   Ship Mode
Central  First Class        58057.2978
         Same Day           20105.9220
         Second Class       97605.7134
         Standard Class    316877.9800
East     First Class       110436.6930
         Same Day           43316.4640
         Second Class      115108.2580
         Standard Class    400657.3110
South    First Class        49045.9160
         Same Day           21017.1730
         Second Class       93434.5365
         Standard Class    225653.8335
West     First Class       128032.3505
         Same Day           40779.4800
         Second Class      143765.6715
         Standard Class    397642.1825
Name: Sales, dtype: float64

In [ ]:
print(
    df.groupby(["Region", "Ship Mode"])["Ship Days"].mean()
)

Region   Ship Mode
Central  First Class       2.308219
         Same Day          0.033898
         Second Class      3.364653
         Standard Class    4.983099
East     First Class       2.214894
         Same Day          0.000000
         Second Class      3.270633
         Standard Class    4.966463
South    First Class       2.120690
         Same Day          0.012048
         Second Class      3.196923
         Standard Class    5.008351
West     First Class       2.098619
         Same Day          0.103825
         Second Class      3.174056
         Standard Class    5.065182
Name: Ship Days, dtype: float64

In [ ]:
print(
    df.groupby("Ship Mode")["Sales"].mean()
)

Ship Mode
First Class       230.228020
Same Day          232.749143
Second Class      236.547939
Standard Class    228.849856
Name: Sales, dtype: float64

In [ ]:
print(
    df.groupby("Ship Mode")[["Ship Days", "Sales"]].mean()
)

                Ship Days       Sales
Ship Mode
First Class      2.179214  230.228020
Same Day         0.044610  232.749143
Second Class     3.249211  236.547939
Standard Class   5.008363  228.849856

In [ ]:
print(
    df.groupby("Region")["Ship Days"].mean()
)

Region
Central    4.065876
East       3.910233
South      3.961202
West       3.930255
Name: Ship Days, dtype: float64

In [ ]:
print(
    df.groupby("Category")["Ship Days"].mean()
)

Category
Furniture          3.926853
Office Supplies    3.984600
Technology         3.923883
Name: Ship Days, dtype: float64

In [ ]:
print(
    df.groupby("Segment")["Ship Days"].mean()
)

Segment
Consumer       3.941384
Corporate      4.021334
Home Office    3.916953
Name: Ship Days, dtype: float64

In [ ]:
print(df["Ship Days"].dtype)
print(df["Ship Days"].unique())

int64
[3 4 7 5 2 6 1 0]

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving train.csv to train.csv

In [ ]:
import pandas as pd
df = pd.read_csv("train.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9800 non-null   int64
 1   Order ID       9800 non-null   object
 2   Order Date     9800 non-null   object
 3   Ship Date      9800 non-null   object
 4   Ship Mode      9800 non-null   object
 5   Customer ID    9800 non-null   object
 6   Customer Name  9800 non-null   object
 7   Segment        9800 non-null   object
 8   Country        9800 non-null   object
 9   City           9800 non-null   object
 10  State          9800 non-null   object
 11  Postal Code    9789 non-null   float64
 12  Region         9800 non-null   object
 13  Product ID     9800 non-null   object
 14  Category       9800 non-null   object
 15  Sub-Category   9800 non-null   object
 16  Product Name   9800 non-null   object
 17  Sales          9800 non-null   float64
dtypes: float64(2), int64(1), object(15)
memory usage: 1.3+ MB

In [ ]:
print(
    (df["Ship Days"].value_counts(normalize=True).sort_index() * 100).round(2)
)

KeyError: 'Ship Days'

In [ ]:
print(df.columns.tolist())

['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State', 'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name', 'Sales']

In [ ]:
df["Order Date"] = pd.to_datetime(
    df["Order Date"],
    format="%d-%m-%Y"
)

df["Ship Date"] = pd.to_datetime(
    df["Ship Date"],
    format="%d-%m-%Y"
)

df["Ship Days"] = (
    df["Ship Date"] - df["Order Date"]
).dt.days

In [ ]:
print(
    (df["Ship Days"].value_counts(normalize=True).sort_index() * 100).round(2)
)

Ship Days
0     5.24
1     3.70
2    13.21
3     9.98
4    27.73
5    21.91
6    11.94
7     6.28
Name: proportion, dtype: float64

In [ ]:
print(
    df[df["Ship Days"].isin([4, 5])]
    .groupby("Ship Mode")
    .size()
)

Ship Mode
First Class          1
Second Class       791
Standard Class    4073
dtype: int64

In [ ]:
print(
    df[
        (df["Ship Days"].isin([4, 5])) &
        (df["Ship Mode"] == "Standard Class")
    ]["Sales"].sum()
)

940930.8426999999

In [ ]:
print(
    df[
        (df["Ship Days"].isin([4, 5])) &
        (df["Ship Mode"] == "Standard Class")
    ]
    .groupby("Region")["Sales"]
    .sum()
)

Region
Central    226626.5772
East       283945.4600
South      175906.3370
West       254452.4685
Name: Sales, dtype: float64

In [ ]:
standard_sales_by_region = (
    df[df["Ship Mode"] == "Standard Class"]
    .groupby("Region")["Sales"]
    .sum()
)

target_sales_by_region = (
    df[
        (df["Ship Mode"] == "Standard Class") &
        (df["Ship Days"].isin([4, 5]))
    ]
    .groupby("Region")["Sales"]
    .sum()
)

print(
    (target_sales_by_region / standard_sales_by_region * 100)
    .round(2)
)

Region
Central    71.52
East       70.87
South      77.95
West       63.99
Name: Sales, dtype: float64

In [ ]:
print(
    df[
        (df["Region"] == "South") &
        (df["Ship Mode"] == "Standard Class") &
        (df["Ship Days"].isin([4, 5]))
    ].shape[0]
)

675

In [ ]:
print(
    df[
        (df["Region"] == "South") &
        (df["Ship Mode"] == "Standard Class") &
        (df["Ship Days"].isin([4, 5]))
    ]
    .groupby("Category")["Sales"]
    .sum()
)

Category
Furniture          50355.402
Office Supplies    50747.609
Technology         74803.326
Name: Sales, dtype: float64

In [ ]:
print(
    df[
        (df["Region"] == "South") &
        (df["Ship Mode"] == "Standard Class") &
        (df["Ship Days"].isin([4, 5])) &
        (df["Category"] == "Technology")
    ]
    .groupby("Sub-Category")["Sales"]
    .sum()
)

Sub-Category
Accessories    11041.786
Copiers         3519.872
Machines       32069.170
Phones         28172.498
Name: Sales, dtype: float64

In [ ]:
print(
    df[
        (df["Region"] == "South") &
        (df["Ship Mode"] == "Standard Class") &
        (df["Ship Days"].isin([4, 5])) &
        (df["Category"] == "Technology") &
        (df["Sub-Category"].isin(["Machines", "Phones"]))
    ]
    .groupby("Product Name")["Sales"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

Product Name
Cisco TelePresence System EX90 Videoconferencing Unit        22638.480
Samsung Galaxy S4 Active                                      3499.930
Cisco 9971 IP Video Phone Charcoal                            3080.000
Samsung Galaxy Mega 6.3                                       2939.930
HP Designjet T520 Inkjet Large Format Printer - 24" Color     2624.985
Samsung Galaxy S III - 16GB - pebble blue (T-Mobile)          2239.936
Cisco SPA301                                                  2121.464
Wilson SignalBoost 841262 DB PRO Amplifier Kit                1439.800
Cisco Unified IP Phone 7945G VoIP phone                       1363.960
HTC One Mini                                                  1335.494
Name: Sales, dtype: float64

In [ ]:
cisco_product = df[
    df["Product Name"] ==
    "Cisco TelePresence System EX90 Videoconferencing Unit"
]

print("Rows:", cisco_product.shape[0])
print("Total Sales:", cisco_product["Sales"].sum())
print("Average Sales:", cisco_product["Sales"].mean())
print("Minimum Sales:", cisco_product["Sales"].min())
print("Maximum Sales:", cisco_product["Sales"].max())

Rows: 1
Total Sales: 22638.48
Average Sales: 22638.48
Minimum Sales: 22638.48
Maximum Sales: 22638.48

In [ ]:
print(
    df[
        (df["Region"] == "South") &
        (df["Ship Mode"] == "Standard Class") &
        (df["Ship Days"].isin([4, 5])) &
        (df["Category"] == "Technology") &
        (df["Sub-Category"].isin(["Machines", "Phones"])) &
        (df["Product Name"] !=
         "Cisco TelePresence System EX90 Videoconferencing Unit")
    ]
    .groupby("Product Name")
    .agg(
        Orders=("Order ID", "count"),
        Sales=("Sales", "sum")
    )
    .sort_values("Sales", ascending=False)
    .head(10)
)

                                                    Orders     Sales
Product Name
Samsung Galaxy S4 Active                                 1  3499.930
Cisco 9971 IP Video Phone Charcoal                       1  3080.000
Samsung Galaxy Mega 6.3                                  1  2939.930
HP Designjet T520 Inkjet Large Format Printer -...       1  2624.985
Samsung Galaxy S III - 16GB - pebble blue (T-Mo...       1  2239.936
Cisco SPA301                                             2  2121.464
Wilson SignalBoost 841262 DB PRO Amplifier Kit           2  1439.800
Cisco Unified IP Phone 7945G VoIP phone                  1  1363.960
HTC One Mini                                             2  1335.494
3D Systems Cube Printer, 2nd Generation, White           1  1299.990

In [ ]:
print(
    df[df["Ship Mode"] == "Standard Class"]
    .pivot_table(
        index="Region",
        columns="Ship Days",
        values="Sales",
        aggfunc="sum",
        fill_value=0
    )
    .div(
        df[df["Ship Mode"] == "Standard Class"]
        .groupby("Region")["Sales"]
        .sum(),
        axis=0
    )
    .mul(100)
    .round(2)
)

Ship Days     3      4      5      6      7
Region
Central    0.01  43.01  28.50  15.57  12.91
East       0.00  45.52  25.35  18.62  10.51
South      0.00  36.07  41.88  14.21   7.84
West       0.00  36.82  27.17  20.05  15.96

In [ ]:
print(
    df[
        (df["Region"] == "South") &
        (df["Ship Mode"] == "Standard Class")
    ]
    .groupby("Ship Days")
    .agg(
        Orders=("Order ID", "count"),
        Sales=("Sales", "sum")
    )
    .sort_index()
)

           Orders       Sales
Ship Days
4             378  81396.2660
5             297  94510.0710
6             180  32058.3020
7             103  17689.1945

In [ ]:
five_day_standard = (
    df[
        (df["Ship Mode"] == "Standard Class") &
        (df["Ship Days"] == 5)
    ]
    .groupby("Region")
    .agg(
        Orders=("Order ID", "count"),
        Sales=("Sales", "sum")
    )
)

five_day_standard["Avg Sales per Order"] = (
    five_day_standard["Sales"] /
    five_day_standard["Orders"]
)

print(five_day_standard.round(2))

         Orders      Sales  Avg Sales per Order
Region
Central     409   90323.08               220.84
East        472  101562.21               215.17
South       297   94510.07               318.22
West        546  108053.01               197.90

In [ ]:
print(
    df[
        (df["Ship Mode"] == "Standard Class") &
        (df["Ship Days"] == 5)
    ]
    .groupby(["Region", "Category"])
    .agg(
        Orders=("Order ID", "count"),
        Sales=("Sales", "sum")
    )
    .assign(
        Avg_Sales_per_Order=lambda x:
        x["Sales"] / x["Orders"]
    )
    .round(2)
)

                         Orders     Sales  Avg_Sales_per_Order
Region  Category
Central Furniture            73  28039.08               384.10
        Office Supplies     270  38615.15               143.02
        Technology           66  23668.84               358.62
East    Furniture            93  29269.86               314.73
        Office Supplies     288  32843.52               114.04
        Technology           91  39448.83               433.50
South   Furniture            65  22855.97               351.63
        Office Supplies     183  24488.22               133.82
        Technology           49  47165.88               962.57
West    Furniture           129  47449.43               367.83
        Office Supplies     326  28810.89                88.38
        Technology           91  31792.68               349.37

In [ ]:
print(
    df[
        (df["Region"] == "South") &
        (df["Ship Mode"] == "Standard Class") &
        (df["Ship Days"] == 5) &
        (df["Category"] == "Technology")
    ][
        ["Order ID", "Product Name", "Sales"]
    ]
    .sort_values("Sales", ascending=False)
    .to_string(index=False)
)

      Order ID                                                                                       Product Name     Sales
CA-2015-145317                                              Cisco TelePresence System EX90 Videoconferencing Unit 22638.480
US-2018-105935                                                                            Samsung Galaxy Mega 6.3  2939.930
CA-2015-127299                                          HP Designjet T520 Inkjet Large Format Printer - 24" Color  2624.985
CA-2018-119284                                               Samsung Galaxy S III - 16GB - pebble blue (T-Mobile)  2239.936
CA-2016-125976                                                                                       Cisco SPA301  1871.880
CA-2017-102162                                                                       Canon PC-428 Personal Copier  1599.920
CA-2017-169103                                                            Cisco Unified IP Phone 7945G VoIP phone  1363.960
US-2017-164630                                                           Hewlett Packard 310 Color Digital Copier   959.968
US-2015-165659                                                                                   Adtran 1202752G1   881.930
CA-2015-145317                                                  Hewlett-Packard Deskjet 6540 Color Inkjet Printer   821.300
CA-2017-118626                                                                                       HTC One Mini   705.544
CA-2015-166051                                                                              Samsung Galaxy Note 3   659.970
CA-2018-117198                                 Plantronics CS510 - Over-the-Head monaural Wireless Headset System   659.900
CA-2018-109183                                                                              Okidata C610n Printer   649.000
CA-2016-158421                                                                                       HTC One Mini   629.950
CA-2015-128846                                                                                       AT&T TR1909W   629.950
US-2018-100930                                                                 Logitech P710e Mobile Speakerphone   617.976
CA-2017-112277                                                                               Geemarc AmpliPOWER60   519.680
US-2017-109260                                  Logitech VX Revolution Cordless Laser Mouse for Notebooks (Black)   431.976
CA-2018-134096                                                                                       Vtech CS6719   383.960
CA-2018-161130                                                               Polycom SoundPoint IP 450 VoIP phone   361.376
CA-2016-149342                                                                                      Pyle PMP37LED   287.970
CA-2016-165624                                                                        Maxell LTO Ultrium - 800 GB   251.910
CA-2016-150308                                                           Cisco Small Business SPA 502G VoIP phone   246.168
CA-2017-113845                                                      Grandstream GXP2100 Mainstream Business Phone   244.768
CA-2018-119284                                                                                            HTC One   239.976
CA-2015-128839                                         Epson WorkForce WF-2530 All-in-One Printer, Copier Scanner   209.970
US-2015-155502                                                                                    Jabra SPEAK 410   187.980
CA-2016-156328                                                                            Avaya 4621SW VoIP phone   177.480
US-2015-155502                                                                          Macally Suction Cup Mount   155.350
CA-2015-166051                                                                     Grandstream GXP1160 VoIP phone   113.730
CA-2016-158421                                                                     Grandstream GXP1160 VoIP phone   113.730
CA-2016-136147                                                                        Maxell LTO Ultrium - 800 GB   111.960
US-2017-137295                                                                           Avaya 5410 Digital phone   108.784
US-2016-168935                                                                       Logitech Media Keyboard K200    83.976
CA-2018-119004                                                 Memorex Mini Travel Drive 8 GB USB 2.0 Flash Drive    74.112
US-2016-123960                                                         Kingston Digital DataTraveler 16GB USB 2.0    53.700
CA-2018-135587                                                                    Memorex Micro Travel Drive 8 GB    52.000
CA-2015-133634                                                                         Maxell 4.7GB DVD-RW 3/Pack    47.790
US-2017-148901 LF Elite 3D Dazzle Designer Hard Case Cover, Lf Stylus Pen and Wiper For Apple Iphone 5c Mini Lite    43.600
CA-2015-102274                                          Logitech B530 USB Headset - headset - Full size, Binaural    36.990
CA-2016-169740                              Anker Ultrathin Bluetooth Wireless Keyboard Aluminum Cover with Stand    29.990
CA-2018-119004                                                                Speck Products Candyshell Flip Case    27.992
CA-2017-123946                                                                  Imation 30456 USB Flash Drive 8GB    20.700
CA-2018-159100                                                 Memorex Mini Travel Drive 8 GB USB 2.0 Flash Drive    18.528
US-2018-115252                                                                            PayAnywhere Card Reader    15.984
CA-2015-138527                                                               SanDisk Cruzer 32 GB USB Flash Drive    15.216
CA-2018-108322                                                                          Maxell 4.7GB DVD+R 5/Pack     2.376
CA-2018-128363                                                                          Maxell 4.7GB DVD-R 5/Pack     1.584

In [ ]:
south_tech_5day = df[
    (df["Region"] == "South") &
    (df["Ship Mode"] == "Standard Class") &
    (df["Ship Days"] == 5) &
    (df["Category"] == "Technology")
]

print("Transactions:", south_tech_5day.shape[0])
print("Mean Sales:", south_tech_5day["Sales"].mean())
print("Median Sales:", south_tech_5day["Sales"].median())
print("Maximum Sales:", south_tech_5day["Sales"].max())

Transactions: 49
Mean Sales: 962.5690816326529
Median Sales: 244.768
Maximum Sales: 22638.48

In [ ]:
print(
    df.groupby("Ship Mode")
    .agg(
        Orders=("Order ID", "count"),
        Avg_Ship_Days=("Ship Days", "mean"),
        Median_Ship_Days=("Ship Days", "median"),
        Min_Ship_Days=("Ship Days", "min"),
        Max_Ship_Days=("Ship Days", "max")
    )
    .round(2)
)

NameError: name 'df' is not defined

In [ ]:
import pandas as pd

from google.colab import files

uploaded = files.upload()

df = pd.read_csv("train.csv")

df["Order Date"] = pd.to_datetime(
    df["Order Date"],
    format="%d-%m-%Y"
)

df["Ship Date"] = pd.to_datetime(
    df["Ship Date"],
    format="%d-%m-%Y"
)

df["Ship Days"] = (
    df["Ship Date"] - df["Order Date"]
).dt.days

print(df.shape)
print(df["Ship Days"].head())

Saving train.csv to train.csv
(9800, 19)
0    3
1    3
2    4
3    7
4    7
Name: Ship Days, dtype: int64

In [ ]:
print(
    df.groupby("Ship Mode")
    .agg(
        Orders=("Order ID", "count"),
        Avg_Ship_Days=("Ship Days", "mean"),
        Median_Ship_Days=("Ship Days", "median"),
        Min_Ship_Days=("Ship Days", "min"),
        Max_Ship_Days=("Ship Days", "max")
    )
    .round(2)
)

                Orders  Avg_Ship_Days  Median_Ship_Days  Min_Ship_Days  \
Ship Mode
First Class       1501           2.18               2.0              1
Same Day           538           0.04               0.0              0
Second Class      1902           3.25               3.0              1
Standard Class    5859           5.01               5.0              3

                Max_Ship_Days
Ship Mode
First Class                 4
Same Day                    1
Second Class                5
Standard Class              7

In [ ]:
print(
    df.groupby("Ship Mode")["Ship Days"]
    .agg(
        Std_Ship_Days="std"
    )
    .round(2)
)

                Std_Ship_Days
Ship Mode
First Class              0.77
Same Day                 0.21
Second Class             1.19
Standard Class           1.01

In [ ]:
print(
    pd.crosstab(
        df["Ship Mode"],
        df["Ship Days"],
        normalize="index"
    )
    .mul(100)
    .round(2)
)

Ship Days           0      1      2      3      4      5      6     7
Ship Mode
First Class      0.00  22.52  37.11  40.31   0.07   0.00   0.00   0.0
Same Day        95.54   4.46   0.00   0.00   0.00   0.00   0.00   0.0
Second Class     0.00   0.05  38.80  19.56  19.35  22.24   0.00   0.0
Standard Class   0.00   0.00   0.00   0.02  40.09  29.42  19.97  10.5

In [ ]:
print(
    df.groupby("Ship Mode")["Ship Days"]
    .agg(lambda x: x.value_counts().idxmax())
)

Ship Mode
First Class       3
Same Day          0
Second Class      2
Standard Class    4
Name: Ship Days, dtype: int64

In [ ]:
print(df.groupby('Ship Mode')['Ship Days']
      .agg(lambda x:x.value_counts().idxmax()))

Ship Mode
First Class       3
Same Day          0
Second Class      2
Standard Class    4
Name: Ship Days, dtype: int64

In [ ]:
print(df.groupby('Ship Mode')['Ship Days'].value_counts())

Ship Mode       Ship Days
First Class     3             605
                2             557
                1             338
                4               1
Same Day        0             514
                1              24
Second Class    2             738
                5             423
                3             372
                4             368
                1               1
Standard Class  4            2349
                5            1724
                6            1170
                7             615
                3               1
Name: count, dtype: int64

In [ ]:
print(
    df.groupby("Ship Mode")["Ship Days"]
    .agg(
        Dominant_Ship_Days=lambda x: x.value_counts().idxmax(),
        Dominant_Share=lambda x: x.value_counts(normalize=True).max() * 100
    )
    .round(2)
)

                Dominant_Ship_Days  Dominant_Share
Ship Mode
First Class                      3           40.31
Same Day                         0           95.54
Second Class                     2           38.80
Standard Class                   4           40.09

In [ ]:
print(
    df.groupby("Ship Mode")["Ship Days"]
    .agg(
        Std_Ship_Days="std"
    )
    .round(2)
)

                Std_Ship_Days
Ship Mode
First Class              0.77
Same Day                 0.21
Second Class             1.19
Standard Class           1.01

In [ ]:
print(
    pd.crosstab(
        df["Ship Mode"],
        df["Ship Days"],
        normalize="index"
    )
    .mul(100)
    .round(2)
)

Ship Days           0      1      2      3      4      5      6     7
Ship Mode
First Class      0.00  22.52  37.11  40.31   0.07   0.00   0.00   0.0
Same Day        95.54   4.46   0.00   0.00   0.00   0.00   0.00   0.0
Second Class     0.00   0.05  38.80  19.56  19.35  22.24   0.00   0.0
Standard Class   0.00   0.00   0.00   0.02  40.09  29.42  19.97  10.5

In [ ]:
print(
    df.groupby("Region")["Ship Days"]
    .agg(
        Orders="count",
        Avg_Ship_Days="mean",
        Median_Ship_Days="median",
        Min_Ship_Days="min",
        Max_Ship_Days="max"
    )
    .round(2)
)

         Orders  Avg_Ship_Days  Median_Ship_Days  Min_Ship_Days  Max_Ship_Days
Region
Central    2277           4.07               4.0              0              7
East       2785           3.91               4.0              0              7
South      1598           3.96               4.0              0              7
West       3140           3.93               4.0              0              7

In [ ]:
print(
    df.groupby("Region")["Ship Days"]
    .agg(
        Std_Ship_Days="std"
    )
    .round(2)
)

         Std_Ship_Days
Region
Central           1.69
East              1.73
South             1.74
West              1.81

In [ ]:
import pandas as pd

from google.colab import files

uploaded = files.upload()

Saving train.csv to train.csv

In [ ]:
df=pd.read_csv('train.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9800 non-null   int64
 1   Order ID       9800 non-null   object
 2   Order Date     9800 non-null   object
 3   Ship Date      9800 non-null   object
 4   Ship Mode      9800 non-null   object
 5   Customer ID    9800 non-null   object
 6   Customer Name  9800 non-null   object
 7   Segment        9800 non-null   object
 8   Country        9800 non-null   object
 9   City           9800 non-null   object
 10  State          9800 non-null   object
 11  Postal Code    9789 non-null   float64
 12  Region         9800 non-null   object
 13  Product ID     9800 non-null   object
 14  Category       9800 non-null   object
 15  Sub-Category   9800 non-null   object
 16  Product Name   9800 non-null   object
 17  Sales          9800 non-null   float64
dtypes: float64(2), int64(1), object(15)
memory usage: 1.3+ MB

In [ ]:
df["Order Date"] = pd.to_datetime(
    df["Order Date"],
    format="%d-%m-%Y"
)

df["Ship Date"] = pd.to_datetime(
    df["Ship Date"],
    format="%d-%m-%Y"
)

df["Ship Days"] = (
    df["Ship Date"] - df["Order Date"]
).dt.days

print(df.shape)
print(df["Ship Days"].head())

(9800, 19)
0    3
1    3
2    4
3    7
4    7
Name: Ship Days, dtype: int64

In [ ]:
del print

In [ ]:
print(df.shape)

(9800, 19)

In [ ]:
print(
    df.groupby("Ship Mode")["Ship Days"]
    .mean()
    .round(2)
)

TypeError: 'Series' object is not callable

In [ ]:
df.groupby("Ship Mode")["Ship Days"].mean().round(2)

Ship Mode
First Class       2.18
Same Day          0.04
Second Class      3.25
Standard Class    5.01
Name: Ship Days, dtype: float64

In [ ]:
df.groupby("Ship Mode")["Ship Days"].std().round(2)

Ship Mode
First Class       0.77
Same Day          0.21
Second Class      1.19
Standard Class    1.01
Name: Ship Days, dtype: float64

In [ ]:
pd.crosstab(
    df["Ship Mode"],
    df["Ship Days"],
    normalize="index"
).mul(100).round(2)

Ship Days           0      1      2      3      4      5      6     7
Ship Mode
First Class      0.00  22.52  37.11  40.31   0.07   0.00   0.00   0.0
Same Day        95.54   4.46   0.00   0.00   0.00   0.00   0.00   0.0
Second Class     0.00   0.05  38.80  19.56  19.35  22.24   0.00   0.0
Standard Class   0.00   0.00   0.00   0.02  40.09  29.42  19.97  10.5

In [ ]:
df.groupby("Ship Mode")["Ship Days"].agg(
    lambda x: x.value_counts().idxmax()
)

Ship Mode
First Class       3
Same Day          0
Second Class      2
Standard Class    4
Name: Ship Days, dtype: int64

In [ ]:
df.groupby("Ship Mode")["Ship Days"].agg(
    Dominant_Ship_Days=lambda x: x.value_counts().idxmax(),
    Dominant_Share=lambda x: x.value_counts(normalize=True).max() * 100
).round(2)

                Dominant_Ship_Days  Dominant_Share
Ship Mode
First Class                      3           40.31
Same Day                         0           95.54
Second Class                     2           38.80
Standard Class                   4           40.09

In [ ]:
df.groupby("Ship Mode")["Ship Days"].agg(
    Avg_Ship_Days="mean",
    Median_Ship_Days="median",
    Std_Ship_Days="std",
    Min_Ship_Days="min",
    Max_Ship_Days="max"
).round(2)

,Avg_Ship_Days,Median_Ship_Days,Std_Ship_Days,Min_Ship_Days,Max_Ship_Days
Ship Mode,,,,,
First Class,2.18,2.0,0.77,1,4
Same Day,0.04,0.0,0.21,0,1
Second Class,3.25,3.0,1.19,1,5
Standard Class,5.01,5.0,1.01,3,7

In [ ]:
df.groupby("Ship Mode").size()

Ship Mode
First Class       1501
Same Day           538
Second Class      1902
Standard Class    5859
dtype: int64

In [ ]:
df["Ship Mode"].value_counts(normalize=True).mul(100).round(2)

Ship Mode
Standard Class    59.79
Second Class      19.41
First Class       15.32
Same Day           5.49
Name: proportion, dtype: float64

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving train.csv to train.csv

In [ ]:
import pandas as pd

df = pd.read_csv("train.csv")

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9800 non-null   int64
 1   Order ID       9800 non-null   object
 2   Order Date     9800 non-null   object
 3   Ship Date      9800 non-null   object
 4   Ship Mode      9800 non-null   object
 5   Customer ID    9800 non-null   object
 6   Customer Name  9800 non-null   object
 7   Segment        9800 non-null   object
 8   Country        9800 non-null   object
 9   City           9800 non-null   object
 10  State          9800 non-null   object
 11  Postal Code    9789 non-null   float64
 12  Region         9800 non-null   object
 13  Product ID     9800 non-null   object
 14  Category       9800 non-null   object
 15  Sub-Category   9800 non-null   object
 16  Product Name   9800 non-null   object
 17  Sales          9800 non-null   float64
dtypes: float64(2), int64(1), object(15)
memory usage: 1.3+ MB

In [ ]:
df["Order Date"] = pd.to_datetime(
    df["Order Date"],
    format="%d-%m-%Y"
)

df["Ship Date"] = pd.to_datetime(
    df["Ship Date"],
    format="%d-%m-%Y"
)

In [ ]:
df.groupby(
    df["Order Date"].dt.year
)["Sales"].sum()

Order Date
2015    479856.2081
2016    459436.0054
2017    600192.5500
2018    722052.0192
Name: Sales, dtype: float64

In [ ]:
annual_sales = (
    df.groupby(df["Order Date"].dt.year)["Sales"]
    .sum()
)

annual_sales_growth = (
    annual_sales
    .pct_change()
    .mul(100)
    .round(2)
)

print(annual_sales_growth)

NameError: name 'df' is not defined

In [ ]:
import pandas as pd

df = pd.read_csv("train.csv")

df["Order Date"] = pd.to_datetime(
    df["Order Date"],
    format="%d-%m-%Y"
)

df["Ship Date"] = pd.to_datetime(
    df["Ship Date"],
    format="%d-%m-%Y"
)

df["Ship Days"] = (
    df["Ship Date"] - df["Order Date"]
).dt.days

print(df.shape)
print(df["Order Date"].dtype)

FileNotFoundError: [Errno 2] No such file or directory: 'train.csv'

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving train.csv to train.csv

In [ ]:
import pandas as pd

df = pd.read_csv("train.csv")

df["Order Date"] = pd.to_datetime(
    df["Order Date"],
    format="%d-%m-%Y"
)

df["Ship Date"] = pd.to_datetime(
    df["Ship Date"],
    format="%d-%m-%Y"
)

df["Ship Days"] = (
    df["Ship Date"] - df["Order Date"]
).dt.days

print(df.shape)
print(df["Order Date"].dtype)

(9800, 19)
datetime64[ns]

In [ ]:
annual_sales = (
    df.groupby(df["Order Date"].dt.year)["Sales"]
    .sum()
)

annual_sales_growth = (
    annual_sales
    .pct_change()
    .mul(100)
    .round(2)
)

print(annual_sales_growth)

Order Date
2015      NaN
2016    -4.26
2017    30.64
2018    20.30
Name: Sales, dtype: float64

In [ ]:
regional_annual_sales=(df.groupby([df["Order Date"].dt.year,'Region'])['Sales'].sum())
print(regional_annual_sales)

Order Date  Region
2015        Central    102920.5206
            East       127652.8190
            South      103374.9055
            West       145907.9630
2016        Central    102425.1724
            East       153225.1830
            South       70076.0825
            West       133709.5675
2017        Central    145673.8800
            East       178511.5380
            South       93535.9035
            West       182471.2285
2018        Central    141627.3402
            East       210129.1860
            South      122164.5675
            West       248130.9255
Name: Sales, dtype: float64

In [ ]:
regional_yoy_growth=(regional_annual_sales.groupby(level='Region').pct_change().mul(100).round(2))
print(regional_yoy_growth)

Order Date  Region
2015        Central      NaN
            East         NaN
            South        NaN
            West         NaN
2016        Central    -0.48
            East       20.03
            South     -32.21
            West       -8.36
2017        Central    42.22
            East       16.50
            South      33.48
            West       36.47
2018        Central    -2.78
            East       17.71
            South      30.61
            West       35.98
Name: Sales, dtype: float64

In [ ]:
sales_2018_region_category = (
    df[
        df["Order Date"].dt.year == 2018
    ]
    .groupby(["Region", "Category"])["Sales"]
    .sum()
)

print(sales_2018_region_category)

Region   Category
Central  Furniture          42562.5212
         Office Supplies    55815.0540
         Technology         43249.7650
East     Furniture          60853.8610
         Office Supplies    63155.2210
         Technology         86120.1040
South    Furniture          37868.2255
         Office Supplies    39772.5120
         Technology         44523.8300
West     Furniture          71029.1795
         Office Supplies    81624.7540
         Technology         95476.9920
Name: Sales, dtype: float64

In [ ]:
region_category_sales = (
    df[
        df["Order Date"].dt.year.isin([2017, 2018])
    ]
    .groupby(
        [df["Order Date"].dt.year, "Region", "Category"]
    )["Sales"]
    .sum()
)

regional_category_yoy = (
    region_category_sales
    .groupby(level=["Region", "Category"])
    .pct_change()
    .mul(100)
    .round(2)
)

print(regional_category_yoy)

Order Date  Region   Category
2017        Central  Furniture            NaN
                     Office Supplies      NaN
                     Technology           NaN
            East     Furniture            NaN
                     Office Supplies      NaN
                     Technology           NaN
            South    Furniture            NaN
                     Office Supplies      NaN
                     Technology           NaN
            West     Furniture            NaN
                     Office Supplies      NaN
                     Technology           NaN
2018        Central  Furniture         -14.42
                     Office Supplies    22.41
                     Technology        -14.09
            East     Furniture          35.34
                     Office Supplies     3.45
                     Technology         18.79
            South    Furniture          35.85
                     Office Supplies    38.88
                     Technology         20.26
            West     Furniture          -3.02
                     Office Supplies    73.19
                     Technology         53.75
Name: Sales, dtype: float64

In [ ]:
west_subcategory_sales = (
    df[
        (df["Region"] == "West") &
        (df["Category"].isin(["Office Supplies", "Technology"])) &
        (df["Order Date"].dt.year.isin([2017, 2018]))
    ]
    .groupby(
        [df["Order Date"].dt.year, "Category", "Sub-Category"]
    )["Sales"]
    .sum()
)

west_subcategory_yoy = (
    west_subcategory_sales
    .groupby(level=["Category", "Sub-Category"])
    .pct_change()
    .mul(100)
    .round(2)
)

print(west_subcategory_yoy)

Order Date  Category         Sub-Category
2017        Office Supplies  Appliances         NaN
                             Art                NaN
                             Binders            NaN
                             Envelopes          NaN
                             Fasteners          NaN
                             Labels             NaN
                             Paper              NaN
                             Storage            NaN
                             Supplies           NaN
            Technology       Accessories        NaN
                             Copiers            NaN
                             Machines           NaN
                             Phones             NaN
2018        Office Supplies  Appliances      169.30
                             Art             143.50
                             Binders         118.05
                             Envelopes       -64.94
                             Fasteners        -2.69
                             Labels           59.52
                             Paper            44.75
                             Storage          91.87
                             Supplies        -68.29
            Technology       Accessories      67.07
                             Copiers         353.24
                             Machines          6.66
                             Phones           -3.65
Name: Sales, dtype: float64

In [ ]:
west_subcategory_sales = (
    df[
        (df["Region"] == "West") &
        (df["Category"].isin(["Office Supplies", "Technology"])) &
        (df["Order Date"].dt.year.isin([2017, 2018]))
    ]
    .groupby(
        [df["Order Date"].dt.year, "Category", "Sub-Category"]
    )["Sales"]
    .sum()
    .unstack(level=0)
)

west_subcategory_sales["Sales_Change"] = (
    west_subcategory_sales[2018] -
    west_subcategory_sales[2017]
)

print(
    west_subcategory_sales
    .sort_values("Sales_Change", ascending=False)
)

Order Date                         2017       2018  Sales_Change
Category        Sub-Category
Technology      Copiers        6499.866  29459.676     22959.810
Office Supplies Binders       12108.333  26402.246     14293.913
                Storage       13040.734  25021.292     11980.558
Technology      Accessories   15446.178  25806.112     10359.934
Office Supplies Appliances     5001.252  13468.140      8466.888
                Paper          6422.742   9296.958      2874.216
                Art            1095.672   2667.916      1572.244
Technology      Machines      14793.559  15778.260       984.701
Office Supplies Labels         1214.054   1936.706       722.652
                Fasteners       249.860    243.136        -6.724
Technology      Phones        25359.120  24432.944      -926.176
Office Supplies Envelopes      1558.602    546.474     -1012.128
                Supplies       6440.110   2041.886     -4398.224

In [ ]:
west_growth_drivers = (
    df[
        (df["Region"] == "West") &
        (df["Sub-Category"].isin([
            "Copiers",
            "Binders",
            "Storage",
            "Accessories",
            "Appliances"
        ])) &
        (df["Order Date"].dt.year.isin([2017, 2018]))
    ]
    .groupby(
        [df["Order Date"].dt.year, "Sub-Category"]
    )["Sales"]
    .agg(
        Transactions="count",
        Total_Sales="sum",
        Avg_Sales="mean",
        Median_Sales="median"
    )
    .round(2)
)

print(west_growth_drivers)

                         Transactions  Total_Sales  Avg_Sales  Median_Sales
Order Date Sub-Category
2017       Accessories             55     15446.18     280.84        116.00
           Appliances              35      5001.25     142.89         65.34
           Binders                137     12108.33      88.38         20.70
           Copiers                  4      6499.87    1624.97       1349.96
           Storage                 54     13040.73     241.50        104.49
2018       Accessories             95     25806.11     271.64        119.98
           Appliances              46     13468.14     292.79        114.46
           Binders                164     26402.25     160.99         25.70
           Copiers                 11     29459.68    2678.15       1199.98
           Storage                100     25021.29     250.21        130.00

In [ ]:
west_customer_growth = (
    df[
        (df["Region"] == "West") &
        (df["Order Date"].dt.year.isin([2017, 2018]))
    ]
    .groupby(df["Order Date"].dt.year)
    .agg(
        Unique_Customers=("Customer ID", "nunique"),
        Transactions=("Order ID", "count"),
        Total_Sales=("Sales", "sum"),
        Avg_Sales_per_Transaction=("Sales", "mean")
    )
    .round(2)
)

print(west_customer_growth)

            Unique_Customers  Transactions  Total_Sales  \
Order Date
2017                     326           787    182471.23
2018                     393          1080    248130.93

            Avg_Sales_per_Transaction
Order Date
2017                           231.86
2018                           229.75

In [ ]:
west_order_growth = (
    df[
        (df["Region"] == "West") &
        (df["Order Date"].dt.year.isin([2017, 2018]))
    ]
    .groupby(df["Order Date"].dt.year)
    .agg(
        Unique_Orders=("Order ID", "nunique"),
        Rows=("Order ID", "count"),
        Unique_Customers=("Customer ID", "nunique"),
        Total_Sales=("Sales", "sum")
    )
)

print(west_order_growth)

            Unique_Orders  Rows  Unique_Customers  Total_Sales
Order Date
2017                  417   787               326  182471.2285
2018                  530  1080               393  248130.9255

In [ ]:
west_order_value = (
    df[
        (df["Region"] == "West") &
        (df["Order Date"].dt.year.isin([2017, 2018]))
    ]
    .groupby(df["Order Date"].dt.year)
    .agg(
        Unique_Orders=("Order ID", "nunique"),
        Total_Sales=("Sales", "sum")
    )
)

west_order_value["Sales_per_Order"] = (
    west_order_value["Total_Sales"] /
    west_order_value["Unique_Orders"]
)

print(west_order_value.round(2))

            Unique_Orders  Total_Sales  Sales_per_Order
Order Date
2017                  417    182471.23           437.58
2018                  530    248130.93           468.17

In [ ]:
west_subcat_order_value = (
    df[
        (df["Region"] == "West") &
        (df["Sub-Category"].isin([
            "Copiers",
            "Binders",
            "Storage",
            "Accessories",
            "Appliances"
        ])) &
        (df["Order Date"].dt.year.isin([2017, 2018]))
    ]
    .groupby(
        [df["Order Date"].dt.year, "Sub-Category"]
    )
    .agg(
        Unique_Orders=("Order ID", "nunique"),
        Total_Sales=("Sales", "sum")
    )
)

west_subcat_order_value["Sales_per_Order"] = (
    west_subcat_order_value["Total_Sales"] /
    west_subcat_order_value["Unique_Orders"]
)

print(west_subcat_order_value.round(2))

                         Unique_Orders  Total_Sales  Sales_per_Order
Order Date Sub-Category
2017       Accessories              50     15446.18           308.92
           Appliances               34      5001.25           147.10
           Binders                 113     12108.33           107.15
           Copiers                   4      6499.87          1624.97
           Storage                  50     13040.73           260.81
2018       Accessories              88     25806.11           293.25
           Appliances               46     13468.14           292.79
           Binders                 142     26402.25           185.93
           Copiers                  11     29459.68          2678.15
           Storage                  94     25021.29           266.18

In [ ]:
west_copier_products = (
    df[
        (df["Region"] == "West") &
        (df["Sub-Category"] == "Copiers") &
        (df["Order Date"].dt.year.isin([2017, 2018]))
    ]
    .groupby(
        [df["Order Date"].dt.year, "Product Name"]
    )
    .agg(
        Orders=("Order ID", "nunique"),
        Sales=("Sales", "sum")
    )
    .sort_index()
)

print(west_copier_products.round(2))

                                                               Orders  \
Order Date Product Name
2017       Canon PC1060 Personal Laser Copier                       1
           Hewlett Packard 310 Color Digital Copier                 1
           Hewlett Packard 610 Color Digital Copier / Printer       2
2018       Brother DCP1000 Digital 3 in 1 Multifunction Ma...       1
           Canon Image Class D660 Copier                            1
           Canon Imageclass D680 Copier / Fax                       1
           Canon imageCLASS 2200 Advanced Copier                    1
           Hewlett Packard 310 Color Digital Copier                 3
           Hewlett Packard LaserJet 3310 Copier                     2
           Sharp 1540cs Digital Laser Copier                        1
           Sharp AL-1530CS Digital Copier                           1

                                                                  Sales
Order Date Product Name
2017       Canon PC1060 Personal Laser Copier                   2799.96
           Hewlett Packard 310 Color Digital Copier             1499.95
           Hewlett Packard 610 Color Digital Copier / Printer   2199.96
2018       Brother DCP1000 Digital 3 in 1 Multifunction Ma...    479.98
           Canon Image Class D660 Copier                        2999.95
           Canon Imageclass D680 Copier / Fax                   3359.95
           Canon imageCLASS 2200 Advanced Copier               13999.96
           Hewlett Packard 310 Color Digital Copier             1259.96
           Hewlett Packard LaserJet 3310 Copier                 5279.91
           Sharp 1540cs Digital Laser Copier                     879.98
           Sharp AL-1530CS Digital Copier                       1199.98

In [ ]:
import pandas as pd
from google.colab import files
upload=files.upload()

Saving train.csv to train.csv

In [ ]:
df=pd.read_csv('train.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9800 non-null   int64
 1   Order ID       9800 non-null   object
 2   Order Date     9800 non-null   object
 3   Ship Date      9800 non-null   object
 4   Ship Mode      9800 non-null   object
 5   Customer ID    9800 non-null   object
 6   Customer Name  9800 non-null   object
 7   Segment        9800 non-null   object
 8   Country        9800 non-null   object
 9   City           9800 non-null   object
 10  State          9800 non-null   object
 11  Postal Code    9789 non-null   float64
 12  Region         9800 non-null   object
 13  Product ID     9800 non-null   object
 14  Category       9800 non-null   object
 15  Sub-Category   9800 non-null   object
 16  Product Name   9800 non-null   object
 17  Sales          9800 non-null   float64
dtypes: float64(2), int64(1), object(15)
memory usage: 1.3+ MB

In [ ]:
df['Order Date']=pd.to_datetime(df['Order Date'],format='%d-%m-%Y')
df['Ship Date']=pd.to_datetime(df['Ship Date'],format='%d-%m-%Y')
print(df)

      Row ID        Order ID Order Date  Ship Date       Ship Mode  \
0          1  CA-2017-152156 2017-11-08 2017-11-11    Second Class
1          2  CA-2017-152156 2017-11-08 2017-11-11    Second Class
2          3  CA-2017-138688 2017-06-12 2017-06-16    Second Class
3          4  US-2016-108966 2016-10-11 2016-10-18  Standard Class
4          5  US-2016-108966 2016-10-11 2016-10-18  Standard Class
...      ...             ...        ...        ...             ...
9795    9796  CA-2017-125920 2017-05-21 2017-05-28  Standard Class
9796    9797  CA-2016-128608 2016-01-12 2016-01-17  Standard Class
9797    9798  CA-2016-128608 2016-01-12 2016-01-17  Standard Class
9798    9799  CA-2016-128608 2016-01-12 2016-01-17  Standard Class
9799    9800  CA-2016-128608 2016-01-12 2016-01-17  Standard Class

     Customer ID     Customer Name    Segment        Country             City  \
0       CG-12520       Claire Gute   Consumer  United States        Henderson
1       CG-12520       Claire Gute   Consumer  United States        Henderson
2       DV-13045   Darrin Van Huff  Corporate  United States      Los Angeles
3       SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale
4       SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale
...          ...               ...        ...            ...              ...
9795    SH-19975     Sally Hughsby  Corporate  United States          Chicago
9796    CS-12490  Cindy Schnelling  Corporate  United States           Toledo
9797    CS-12490  Cindy Schnelling  Corporate  United States           Toledo
9798    CS-12490  Cindy Schnelling  Corporate  United States           Toledo
9799    CS-12490  Cindy Schnelling  Corporate  United States           Toledo

           State  Postal Code   Region       Product ID         Category  \
0       Kentucky      42420.0    South  FUR-BO-10001798        Furniture
1       Kentucky      42420.0    South  FUR-CH-10000454        Furniture
2     California      90036.0     West  OFF-LA-10000240  Office Supplies
3        Florida      33311.0    South  FUR-TA-10000577        Furniture
4        Florida      33311.0    South  OFF-ST-10000760  Office Supplies
...          ...          ...      ...              ...              ...
9795    Illinois      60610.0  Central  OFF-BI-10003429  Office Supplies
9796        Ohio      43615.0     East  OFF-AR-10001374  Office Supplies
9797        Ohio      43615.0     East  TEC-PH-10004977       Technology
9798        Ohio      43615.0     East  TEC-PH-10000912       Technology
9799        Ohio      43615.0     East  TEC-AC-10000487       Technology

     Sub-Category                                       Product Name  \
0       Bookcases                  Bush Somerset Collection Bookcase
1          Chairs  Hon Deluxe Fabric Upholstered Stacking Chairs,...
2          Labels  Self-Adhesive Address Labels for Typewriters b...
3          Tables      Bretford CR4500 Series Slim Rectangular Table
4         Storage                     Eldon Fold 'N Roll Cart System
...           ...                                                ...
9795      Binders  Cardinal HOLDit! Binder Insert Strips,Extra St...
9796          Art           BIC Brite Liner Highlighters, Chisel Tip
9797       Phones                                        GE 30524EE4
9798       Phones           Anker 24W Portable Micro USB Car Charger
9799  Accessories                SanDisk Cruzer 4 GB USB Flash Drive

         Sales  Ship Days
0     261.9600          3
1     731.9400          3
2      14.6200          4
3     957.5775          7
4      22.3680          7
...        ...        ...
9795    3.7980          7
9796   10.3680          5
9797  235.1880          5
9798   26.3760          5
9799   10.3840          5

[9800 rows x 19 columns]

In [ ]:
west_copiers_2018 = df[
    (df["Region"] == "West") &
    (df["Sub-Category"] == "Copiers") &
    (df["Order Date"].dt.year == 2018)
]

total_copier_sales = west_copiers_2018["Sales"].sum()

canon_sales = west_copiers_2018.loc[
    west_copiers_2018["Product Name"] ==
    "Canon imageCLASS 2200 Advanced Copier",
    "Sales"
].sum()

print("Total West Copier Sales:", round(total_copier_sales, 2))
print("Canon Copier Sales:", round(canon_sales, 2))
print(
    "Canon Sales Concentration (%):",
    round(canon_sales / total_copier_sales * 100, 2)
)

Total West Copier Sales: 29459.68
Canon Copier Sales: 13999.96
Canon Sales Concentration (%): 47.52

In [ ]:
west_copier_comparison = (
    df[
        (df["Region"] == "West") &
        (df["Sub-Category"] == "Copiers") &
        (df["Order Date"].dt.year.isin([2017, 2018]))
    ]
    .groupby(df["Order Date"].dt.year)
    .agg(
        Unique_Orders=("Order ID", "nunique"),
        Total_Sales=("Sales", "sum")
    )
)

west_copier_comparison["Sales_per_Order"] = (
    west_copier_comparison["Total_Sales"] /
    west_copier_comparison["Unique_Orders"]
)

print(west_copier_comparison.round(2))

            Unique_Orders  Total_Sales  Sales_per_Order
Order Date
2017                    4      6499.87          1624.97
2018                   11     29459.68          2678.15

In [ ]:
west_copier_customers = (
    df[
        (df["Region"] == "West") &
        (df["Sub-Category"] == "Copiers") &
        (df["Order Date"].dt.year.isin([2017, 2018]))
    ]
    .groupby(df["Order Date"].dt.year)
    .agg(
        Unique_Customers=("Customer ID", "nunique"),
        Unique_Orders=("Order ID", "nunique"),
        Total_Sales=("Sales", "sum")
    )
)

print(west_copier_customers.round(2))

            Unique_Customers  Unique_Orders  Total_Sales
Order Date
2017                       4              4      6499.87
2018                      11             11     29459.68

In [ ]:
import pandas as pd


from google.colab import files
uploaded = files.upload()

Saving train.csv to train.csv

In [ ]:
df = pd.read_csv("train.csv")
print("Dataset shape:", df.shape)
df.head()

Dataset shape: (9800, 18)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08-11-2017,11-11-2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08-11-2017,11-11-2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12-06-2017,16-06-2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11-10-2016,18-10-2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11-10-2016,18-10-2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680

In [ ]:

df["Order Date"] = pd.to_datetime(
    df["Order Date"], format="%d-%m-%Y"
)

df["Ship Date"] = pd.to_datetime(
    df["Ship Date"], format="%d-%m-%Y"
)

df["Ship Days"] = (
    df["Ship Date"] - df["Order Date"]
).dt.days

print(df.shape)

(9800, 19)

In [ ]:

west_copier_2018 = df[
    (df["Region"] == "West") &
    (df["Sub-Category"] == "Copiers") &
    (df["Order Date"].dt.year == 2018)
]

customer_sales = (
    west_copier_2018
    .groupby("Customer ID")["Sales"]
    .sum()
    .sort_values(ascending=False)
)

print("Unique customers:", customer_sales.count())
print("Median customer Sales:", round(customer_sales.median(), 2))
print("Maximum customer Sales:", round(customer_sales.max(), 2))

print("\nTop 5 customers by Sales:")
print(customer_sales.head(5))

Unique customers: 11
Median customer Sales: 1199.98
Maximum customer Sales: 13999.96

Top 5 customers by Sales:
Customer ID
RB-19360    13999.960
PS-19045     3359.952
AD-10180     2999.950
RM-19675     2879.952
HR-14830     2399.960
Name: Sales, dtype: float64

In [ ]:

top_customer_sales = customer_sales.iloc[0]
total_customer_sales = customer_sales.sum()

top_customer_share = (
    top_customer_sales / total_customer_sales
) * 100

print("Top customer Sales:", round(top_customer_sales, 2))
print("Total customer Sales:", round(total_customer_sales, 2))
print("Top customer Sales share (%):", round(top_customer_share, 2))

Top customer Sales: 13999.96
Total customer Sales: 29459.68
Top customer Sales share (%): 47.52

In [ ]:

top_customer_detail = west_copier_2018[
    west_copier_2018["Customer ID"] == "RB-19360"
][
    ["Order ID", "Customer ID", "Product Name", "Sales"]
]

print(top_customer_detail)

            Order ID Customer ID                           Product Name  \
8153  CA-2018-140151    RB-19360  Canon imageCLASS 2200 Advanced Copier

         Sales
8153  13999.96

In [ ]:

customer_2018_purchases = df[
    (df["Customer ID"] == "RB-19360") &
    (df["Order Date"].dt.year == 2018)
]

customer_2018_summary = customer_2018_purchases.agg(
    Unique_Orders=("Order ID", "nunique"),
    Unique_Products=("Product Name", "nunique"),
    Total_Sales=("Sales", "sum")
)

print(customer_2018_summary)
print("\nProducts purchased:")
print(
    customer_2018_purchases[
        ["Order ID", "Product Name", "Sales"]
    ]
)

                 Order ID  Product Name      Sales
Unique_Orders         3.0           NaN        NaN
Unique_Products       NaN           6.0        NaN
Total_Sales           NaN           NaN  14203.278

Products purchased:
            Order ID                                       Product Name  \
2855  CA-2018-169810                                          Avery 498
3142  CA-2018-162572  Logitech 910-002974 M325 Wireless Mouse for We...
3143  CA-2018-162572                                         Newell 311
8151  CA-2018-140151           Acco Perma 4000 Stacking Storage Drawers
8152  CA-2018-140151                                         Xerox 1898
8153  CA-2018-140151              Canon imageCLASS 2200 Advanced Copier

          Sales
2855     20.230
3142    119.960
3143     10.608
8151     32.480
8152     20.040
8153  13999.960

In [ ]:

customer_order_summary = (
    customer_2018_purchases
    .groupby("Order ID")
    .agg(
        Unique_Products=("Product Name", "nunique"),
        Total_Sales=("Sales", "sum")
    )
    .sort_values("Total_Sales", ascending=False)
)

print(customer_order_summary.round(2))

                Unique_Products  Total_Sales
Order ID
CA-2018-140151                3     14052.48
CA-2018-162572                2       130.57
CA-2018-169810                1        20.23

In [ ]:

large_order = customer_2018_purchases[
    customer_2018_purchases["Order ID"] == "CA-2018-140151"
]

order_total = large_order["Sales"].sum()

canon_order_sales = large_order.loc[
    large_order["Product Name"] ==
    "Canon imageCLASS 2200 Advanced Copier",
    "Sales"
].sum()

print("Order total:", round(order_total, 2))
print("Canon Sales:", round(canon_order_sales, 2))
print(
    "Canon share of order (%):",
    round(canon_order_sales / order_total * 100, 2)
)

Order total: 14052.48
Canon Sales: 13999.96
Canon share of order (%): 99.63

In [ ]:

customer_total_sales = customer_2018_purchases["Sales"].sum()
top_order_sales = large_order["Sales"].sum()

print("Customer total Sales:", round(customer_total_sales, 2))
print("Top order Sales:", round(top_order_sales, 2))
print(
    "Top order share of customer Sales (%):",
    round(top_order_sales / customer_total_sales * 100, 2)
)

Customer total Sales: 14203.28
Top order Sales: 14052.48
Top order share of customer Sales (%): 98.94

In [ ]:

customer_concentration = customer_sales.to_frame(
    name="Customer_Sales"
)

customer_concentration["Sales_Share_Pct"] = (
    customer_concentration["Customer_Sales"]
    / customer_concentration["Customer_Sales"].sum()
) * 100

print(customer_concentration.head(3).round(2))

             Customer_Sales  Sales_Share_Pct
Customer ID
RB-19360           13999.96            47.52
PS-19045            3359.95            11.41
AD-10180            2999.95            10.18

In [ ]:

top_3_sales = customer_concentration.head(3)["Customer_Sales"].sum()

total_sales = customer_concentration["Customer_Sales"].sum()

top_3_share = (top_3_sales / total_sales) * 100

print("Top 3 customer Sales:", round(top_3_sales, 2))
print("Total Sales:", round(total_sales, 2))
print("Top 3 Sales share (%):", round(top_3_share, 2))

Top 3 customer Sales: 20359.86
Total Sales: 29459.68
Top 3 Sales share (%): 69.11

In [ ]:

top_customer_sales = customer_sales.iloc[0]

other_customers_sales = (
    customer_sales.drop(customer_sales.index[0]).sum()
)

print("Top customer Sales:", round(top_customer_sales, 2))
print("Other customers Sales:", round(other_customers_sales, 2))
print(
    "Top customer share (%):",
    round((top_customer_sales / customer_sales.sum()) * 100, 2)
)

Top customer Sales: 13999.96
Other customers Sales: 15459.72
Top customer share (%): 47.52

In [ ]:

west_copier_2017 = df[
    (df["Region"] == "West") &
    (df["Sub-Category"] == "Copiers") &
    (df["Order Date"].dt.year == 2017)
]

customer_sales_2017 = (
    west_copier_2017
    .groupby("Customer ID")["Sales"]
    .sum()
    .sort_values(ascending=False)
)

print("Unique customers:", customer_sales_2017.count())
print("Total Sales:", round(customer_sales_2017.sum(), 2))
print("Top customer Sales:", round(customer_sales_2017.iloc[0], 2))
print(
    "Top customer share (%):",
    round(
        customer_sales_2017.iloc[0] / customer_sales_2017.sum() * 100,
        2
    )
)

Unique customers: 4
Total Sales: 6499.87
Top customer Sales: 2799.96
Top customer share (%): 43.08

In [ ]:

print("Top 3 customers in 2017:")
print(customer_sales_2017.head(3).round(2))

Top 3 customers in 2017:
Customer ID
CC-12370    2799.96
EM-14140    1499.95
YC-21895    1199.98
Name: Sales, dtype: float64

In [ ]:

top_3_sales_2017 = customer_sales_2017.head(3).sum()
total_sales_2017 = customer_sales_2017.sum()

top_3_share_2017 = (
    top_3_sales_2017 / total_sales_2017
) * 100

print("Top 3 customer Sales:", round(top_3_sales_2017, 2))
print("Total Sales:", round(total_sales_2017, 2))
print("Top 3 Sales share (%):", round(top_3_share_2017, 2))

Top 3 customer Sales: 5499.89
Total Sales: 6499.87
Top 3 Sales share (%): 84.62

In [ ]:

other_customers_sales_2017 = (
    total_sales_2017 - top_3_sales_2017
)

top_3_sales_2018 = customer_concentration.head(3)["Customer_Sales"].sum()
total_sales_2018 = customer_concentration["Customer_Sales"].sum()

other_customers_sales_2018 = (
    total_sales_2018 - top_3_sales_2018
)

other_customer_growth = (
    (other_customers_sales_2018 - other_customers_sales_2017)
    / other_customers_sales_2017
) * 100

print("2017 Sales outside top 3:", round(other_customers_sales_2017, 2))
print("2018 Sales outside top 3:", round(other_customers_sales_2018, 2))
print("Growth in Sales outside top 3 (%):", round(other_customer_growth, 2))

2017 Sales outside top 3: 999.98
2018 Sales outside top 3: 9099.81
Growth in Sales outside top 3 (%): 810.0

In [ ]:

total_sales_2017 = customer_sales_2017.sum()
total_sales_2018 = customer_sales.sum()

total_sales_increase = total_sales_2018 - total_sales_2017

other_customers_increase = (
    other_customers_sales_2018 - other_customers_sales_2017
)

other_customers_contribution_pct = (
    other_customers_increase / total_sales_increase
) * 100

print("Total Sales increase:", round(total_sales_increase, 2))
print("Increase outside top 3:", round(other_customers_increase, 2))
print(
    "Contribution from outside top 3 (%):",
    round(other_customers_contribution_pct, 2)
)

Total Sales increase: 22959.81
Increase outside top 3: 8099.83
Contribution from outside top 3 (%): 35.28

In [ ]:

top_3_sales_2017 = customer_sales_2017.head(3).sum()
top_3_sales_2018 = customer_sales.head(3).sum()

top_3_increase = top_3_sales_2018 - top_3_sales_2017
other_customers_increase = (
    other_customers_sales_2018 - other_customers_sales_2017
)

total_sales_increase = total_sales_2018 - total_sales_2017

top_3_contribution_pct = (
    top_3_increase / total_sales_increase
) * 100

other_contribution_pct = (
    other_customers_increase / total_sales_increase
) * 100

print("Top 3 Sales increase:", round(top_3_increase, 2))
print("Top 3 contribution (%):", round(top_3_contribution_pct, 2))
print("Other customers contribution (%):", round(other_contribution_pct, 2))
print(
    "Combined contribution (%):",
    round(top_3_contribution_pct + other_contribution_pct, 2)
)

Top 3 Sales increase: 14859.98
Top 3 contribution (%): 64.72
Other customers contribution (%): 35.28
Combined contribution (%): 100.0

In [ ]:

concentration_summary = pd.DataFrame({
    "Metric": [
        "Total Sales",
        "Top 3 customer Sales",
        "Top 3 Sales share (%)",
        "Sales outside top 3",
        "Sales increase",
        "Top 3 contribution to increase (%)",
        "Other customers contribution to increase (%)"
    ],
    "2017": [
        total_sales_2017,
        top_3_sales_2017,
        (top_3_sales_2017 / total_sales_2017) * 100,
        other_customers_sales_2017,
        None,
        None,
        None
    ],
    "2018": [
        total_sales_2018,
        top_3_sales_2018,
        (top_3_sales_2018 / total_sales_2018) * 100,
        other_customers_sales_2018,
        total_sales_increase,
        top_3_contribution_pct,
        other_contribution_pct
    ]
})

print(concentration_summary.round(2).to_string(index=False))

                                      Metric    2017     2018
                                 Total Sales 6499.87 29459.68
                        Top 3 customer Sales 5499.89 20359.86
                       Top 3 Sales share (%)   84.62    69.11
                         Sales outside top 3  999.98  9099.81
                              Sales increase     NaN 22959.81
          Top 3 contribution to increase (%)     NaN    64.72
Other customers contribution to increase (%)     NaN    35.28

In [ ]:

print("2018 total Sales:", repr(total_sales_2018))
print("2018 top 3 Sales:", repr(top_3_sales_2018))
print(
    "2018 Sales outside top 3:",
    repr(total_sales_2018 - top_3_sales_2018)
)
print(
    "2018 Sales outside top 3 (from customer series):",
    repr(customer_sales.sum() - customer_sales.head(3).sum())
)

2018 total Sales: np.float64(29459.676000000003)
2018 top 3 Sales: np.float64(20359.862)
2018 Sales outside top 3: np.float64(9099.814000000002)
2018 Sales outside top 3 (from customer series): np.float64(9099.814000000002)

In [ ]:

west_sales_2018 = df[
    (df["Region"] == "West") &
    (df["Order Date"].dt.year == 2018)
]

west_customer_sales_2018 = (
    west_sales_2018
    .groupby("Customer ID")["Sales"]
    .sum()
    .sort_values(ascending=False)
)

top_copier_customer_west_sales = (
    west_customer_sales_2018.get("RB-19360", 0)
)

west_total_sales_2018 = west_sales_2018["Sales"].sum()

print("RB-19360 total West Sales:", round(top_copier_customer_west_sales, 2))
print("Total West Sales:", round(west_total_sales_2018, 2))
print(
    "Customer share of West Sales (%):",
    round(
        top_copier_customer_west_sales / west_total_sales_2018 * 100,
        2
    )
)

RB-19360 total West Sales: 14052.48
Total West Sales: 248130.93
Customer share of West Sales (%): 5.66

In [ ]:

west_unique_customers_2018 = west_customer_sales_2018.count()

average_sales_per_customer = (
    west_total_sales_2018 / west_unique_customers_2018
)

customer_vs_average = (
    top_copier_customer_west_sales / average_sales_per_customer
)

print("Unique West customers:", west_unique_customers_2018)
print("Average Sales per customer:", round(average_sales_per_customer, 2))
print("RB-19360 Sales:", round(top_copier_customer_west_sales, 2))
print("Customer / regional average:", round(customer_vs_average, 2), "times")

Unique West customers: 393
Average Sales per customer: 631.38
RB-19360 Sales: 14052.48
Customer / regional average: 22.26 times

In [ ]:

west_customer_median = west_customer_sales_2018.median()

customer_vs_median = (
    top_copier_customer_west_sales / west_customer_median
)

print("Median Sales per customer:", round(west_customer_median, 2))
print("RB-19360 Sales:", round(top_copier_customer_west_sales, 2))
print("Customer / regional median:", round(customer_vs_median, 2), "times")

Median Sales per customer: 291.35
RB-19360 Sales: 14052.48
Customer / regional median: 48.23 times

In [ ]:

customer_benchmark_summary = pd.DataFrame({
    "Metric": [
        "Unique customers",
        "Total West Sales",
        "Average Sales per customer",
        "Median Sales per customer",
        "RB-19360 Sales",
        "RB-19360 share of West Sales (%)",
        "RB-19360 / average (times)",
        "RB-19360 / median (times)"
    ],
    "Value": [
        west_unique_customers_2018,
        west_total_sales_2018,
        average_sales_per_customer,
        west_customer_median,
        top_copier_customer_west_sales,
        (top_copier_customer_west_sales / west_total_sales_2018) * 100,
        customer_vs_average,
        customer_vs_median
    ]
})

print(customer_benchmark_summary.round(2).to_string(index=False))

                          Metric     Value
                Unique customers    393.00
                Total West Sales 248130.93
      Average Sales per customer    631.38
       Median Sales per customer    291.35
                  RB-19360 Sales  14052.48
RB-19360 share of West Sales (%)      5.66
      RB-19360 / average (times)     22.26
       RB-19360 / median (times)     48.23

In [ ]:

monthly_sales = (
    df.groupby(df["Order Date"].dt.month)["Sales"]
    .sum()
    .sort_index()
)

print(monthly_sales.round(2))

Order Date
1      94291.63
2      59371.12
3     197573.59
4     136283.00
5     154086.72
6     145837.52
7     145535.69
8     157315.93
9     300103.41
10    199496.29
11    350161.71
12    321480.17
Name: Sales, dtype: float64

In [ ]:

monthly_sales_by_year = df.pivot_table(
    index=df["Order Date"].dt.month,
    columns=df["Order Date"].dt.year,
    values="Sales",
    aggfunc="sum"
)

print(monthly_sales_by_year.round(2))

Order Date      2015      2016      2017       2018
Order Date
1           14205.71  18066.96  18542.49   43476.47
2            4519.89  11951.41  22978.82   19921.00
3           55205.80  32339.32  51165.06   58863.41
4           27906.86  34154.47  38679.77   35541.91
5           23644.30  29959.53  56656.91   43825.98
6           34322.94  23599.37  39724.49   48190.73
7           33781.54  28608.26  38320.78   44825.10
8           27117.54  36818.34  30542.20   62837.85
9           81623.53  63133.61  69193.39   86152.89
10          31453.39  31011.74  59583.03   77448.13
11          77907.66  75249.40  79066.50  117938.16
12          68167.06  74543.60  95739.12   83030.39

In [ ]:

monthly_yoy_growth = monthly_sales_by_year.pct_change(axis=1) * 100

print(monthly_yoy_growth.round(2))

Order Date  2015    2016   2017    2018
Order Date
1            NaN   27.18   2.63  134.47
2            NaN  164.42  92.27  -13.31
3            NaN  -41.42  58.21   15.05
4            NaN   22.39  13.25   -8.11
5            NaN   26.71  89.11  -22.65
6            NaN  -31.24  68.33   21.31
7            NaN  -15.31  33.95   16.97
8            NaN   35.77 -17.05  105.74
9            NaN  -22.65   9.60   24.51
10           NaN   -1.40  92.13   29.98
11           NaN   -3.41   5.07   49.16
12           NaN    9.35  28.43  -13.27

In [ ]:

monthly_orders_by_year = df.pivot_table(
    index=df["Order Date"].dt.month,
    columns=df["Order Date"].dt.year,
    values="Order ID",
    aggfunc="nunique"
)

print(monthly_orders_by_year)

Order Date  2015  2016  2017  2018
Order Date
1             30    29    48    67
2             28    36    45    52
3             69    75    85   117
4             63    71    88   115
5             68    72   107   116
6             64    66    95   129
7             64    64    95   108
8             70    67    89   109
9            129   137   186   222
10            78    86   103   144
11           145   157   182   259
12           139   159   172   223

In [ ]:

monthly_sales_per_order = (
    monthly_sales_by_year / monthly_orders_by_year
)

print(monthly_sales_per_order.round(2))

Order Date    2015    2016    2017    2018
Order Date
1           473.52  623.00  386.30  648.90
2           161.42  331.98  510.64  383.10
3           800.08  431.19  601.94  503.11
4           442.97  481.05  439.54  309.06
5           347.71  416.10  529.50  377.81
6           536.30  357.57  418.15  373.57
7           527.84  447.00  403.38  415.05
8           387.39  549.53  343.17  576.49
9           632.74  460.83  372.01  388.08
10          403.25  360.60  578.48  537.83
11          537.29  479.30  434.43  455.36
12          490.41  468.83  556.62  372.33

In [ ]:

monthly_order_value_growth = (
    monthly_sales_per_order.pct_change(axis=1) * 100
)

print(monthly_order_value_growth.round(2))

Order Date  2015    2016   2017   2018
Order Date
1            NaN   31.57 -37.99  67.98
2            NaN  105.66  53.81 -24.98
3            NaN  -46.11  39.60 -16.42
4            NaN    8.60  -8.63 -29.69
5            NaN   19.67  27.25 -28.65
6            NaN  -33.33  16.94 -10.66
7            NaN  -15.31  -9.76   2.89
8            NaN   41.85 -37.55  67.99
9            NaN  -27.17 -19.27   4.32
10           NaN  -10.58  60.42  -7.03
11           NaN  -10.79  -9.36   4.82
12           NaN   -4.40  18.73 -33.11

In [ ]:

monthly_orders_growth = (
    monthly_orders_by_year.pct_change(axis=1) * 100
)

monthly_comparison_2018 = pd.DataFrame({
    "Sales_Growth_Pct": monthly_yoy_growth[2018],
    "Orders_Growth_Pct": monthly_orders_growth[2018],
    "Avg_Sales_Per_Order_Growth_Pct": monthly_order_value_growth[2018]
})

print(monthly_comparison_2018.round(2))

            Sales_Growth_Pct  Orders_Growth_Pct  \
Order Date
1                     134.47              39.58
2                     -13.31              15.56
3                      15.05              37.65
4                      -8.11              30.68
5                     -22.65               8.41
6                      21.31              35.79
7                      16.97              13.68
8                     105.74              22.47
9                      24.51              19.35
10                     29.98              39.81
11                     49.16              42.31
12                    -13.27              29.65

            Avg_Sales_Per_Order_Growth_Pct
Order Date
1                                    67.98
2                                   -24.98
3                                   -16.42
4                                   -29.69
5                                   -28.65
6                                   -10.66
7                                     2.89
8                                    67.99
9                                     4.32
10                                   -7.03
11                                    4.82
12                                  -33.11

In [ ]:

monthly_comparison_2018_sorted = (
    monthly_comparison_2018
    .sort_values("Sales_Growth_Pct", ascending=False)
)

print(monthly_comparison_2018_sorted.round(2))

            Sales_Growth_Pct  Orders_Growth_Pct  \
Order Date
1                     134.47              39.58
8                     105.74              22.47
11                     49.16              42.31
10                     29.98              39.81
9                      24.51              19.35
6                      21.31              35.79
7                      16.97              13.68
3                      15.05              37.65
4                      -8.11              30.68
12                    -13.27              29.65
2                     -13.31              15.56
5                     -22.65               8.41

            Avg_Sales_Per_Order_Growth_Pct
Order Date
1                                    67.98
8                                    67.99
11                                    4.82
10                                   -7.03
9                                     4.32
6                                   -10.66
7                                     2.89
3                                   -16.42
4                                   -29.69
12                                  -33.11
2                                   -24.98
5                                   -28.65

In [ ]:

monthly_sales_change = (
    monthly_sales_by_year[2018] - monthly_sales_by_year[2017]
).to_frame(name="Sales_Change")

monthly_sales_change["Sales_Growth_Pct"] = (
    monthly_yoy_growth[2018]
)

print(
    monthly_sales_change
    .sort_values("Sales_Change", ascending=False)
    .round(2)
)

            Sales_Change  Sales_Growth_Pct
Order Date
11              38871.66             49.16
8               32295.65            105.74
1               24933.98            134.47
10              17865.10             29.98
9               16959.50             24.51
6                8466.24             21.31
3                7698.35             15.05
7                6504.32             16.97
2               -3057.82            -13.31
4               -3137.86             -8.11
12             -12708.73            -13.27
5              -12830.93            -22.65

In [ ]:

positive_sales_change = monthly_sales_change.loc[
    monthly_sales_change["Sales_Change"] > 0,
    "Sales_Change"
].sum()

negative_sales_change = monthly_sales_change.loc[
    monthly_sales_change["Sales_Change"] < 0,
    "Sales_Change"
].sum()

net_sales_change = monthly_sales_change["Sales_Change"].sum()

print("Total positive monthly changes:", round(positive_sales_change, 2))
print("Total negative monthly changes:", round(negative_sales_change, 2))
print("Net annual Sales change:", round(net_sales_change, 2))

Total positive monthly changes: 153594.8
Total negative monthly changes: -31735.33
Net annual Sales change: 121859.47

In [ ]:

decline_offset_pct = (
    abs(negative_sales_change) / positive_sales_change
) * 100

print("Positive monthly gains:", round(positive_sales_change, 2))
print("Absolute negative changes:", round(abs(negative_sales_change), 2))
print("Share of gains offset by declines (%):", round(decline_offset_pct, 2))

Positive monthly gains: 153594.8
Absolute negative changes: 31735.33
Share of gains offset by declines (%): 20.66

In [ ]:

monthly_sales_contribution = monthly_sales_change.copy()

monthly_sales_contribution["Contribution_to_Net_Change_Pct"] = (
    monthly_sales_contribution["Sales_Change"]
    / net_sales_change
) * 100

print(
    monthly_sales_contribution
    .sort_values("Contribution_to_Net_Change_Pct", ascending=False)
    .round(2)
)

            Sales_Change  Sales_Growth_Pct  Contribution_to_Net_Change_Pct
Order Date
11              38871.66             49.16                           31.90
8               32295.65            105.74                           26.50
1               24933.98            134.47                           20.46
10              17865.10             29.98                           14.66
9               16959.50             24.51                           13.92
6                8466.24             21.31                            6.95
3                7698.35             15.05                            6.32
7                6504.32             16.97                            5.34
2               -3057.82            -13.31                           -2.51
4               -3137.86             -8.11                           -2.57
12             -12708.73            -13.27                          -10.43
5              -12830.93            -22.65                          -10.53

In [ ]:

total_monthly_contribution_pct = (
    monthly_sales_contribution["Contribution_to_Net_Change_Pct"].sum()
)

print(
    "Combined monthly contribution (%):",
    round(total_monthly_contribution_pct, 2)
)

Combined monthly contribution (%): 100.0

In [ ]:

november_sales_by_category = df[
    (df["Order Date"].dt.month == 11) &
    (df["Order Date"].dt.year.isin([2017, 2018]))
].pivot_table(
    index="Category",
    columns=df["Order Date"].dt.year,
    values="Sales",
    aggfunc="sum"
)

november_sales_by_category["Sales_Change"] = (
    november_sales_by_category[2018] -
    november_sales_by_category[2017]
)

print(november_sales_by_category.round(2))

Order Date           2017      2018  Sales_Change
Category
Furniture        31783.63  37056.72       5273.09
Office Supplies  20141.81  31472.34      11330.53
Technology       27141.06  49409.10      22268.04

In [ ]:

november_technology = df[
    (df["Order Date"].dt.month == 11) &
    (df["Order Date"].dt.year.isin([2017, 2018])) &
    (df["Category"] == "Technology")
]

november_technology_by_subcategory = november_technology.pivot_table(
    index="Sub-Category",
    columns=november_technology["Order Date"].dt.year,
    values="Sales",
    aggfunc="sum",
    fill_value=0
)

november_technology_by_subcategory["Sales_Change"] = (
    november_technology_by_subcategory[2018] -
    november_technology_by_subcategory[2017]
)

print(
    november_technology_by_subcategory
    .sort_values("Sales_Change", ascending=False)
    .round(2)
)

Order Date       2017      2018  Sales_Change
Sub-Category
Copiers       1199.98  12359.94      11159.96
Phones        9103.07  17201.04       8097.97
Machines      8756.64  11761.38       3004.74
Accessories   8081.38   8086.75          5.37

In [ ]:

november_copiers = df[
    (df["Order Date"].dt.month == 11) &
    (df["Order Date"].dt.year.isin([2017, 2018])) &
    (df["Sub-Category"] == "Copiers")
]

november_copier_summary = november_copiers.groupby(
    november_copiers["Order Date"].dt.year
).agg(
    Unique_Orders=("Order ID", "nunique"),
    Total_Sales=("Sales", "sum")
)

november_copier_summary["Sales_per_Order"] = (
    november_copier_summary["Total_Sales"] /
    november_copier_summary["Unique_Orders"]
)

print(november_copier_summary.round(2))

            Unique_Orders  Total_Sales  Sales_per_Order
Order Date
2017                    1      1199.98          1199.98
2018                    3     12359.94          4119.98

In [ ]:

print(
    november_copiers[
        ["Order Date", "Order ID", "Customer ID", "Product Name", "Sales"]
    ]
    .sort_values("Order Date")
    .to_string(index=False)
)

Order Date       Order ID Customer ID                                       Product Name     Sales
2017-11-14 CA-2017-121370    EB-14110                     Sharp AL-1530CS Digital Copier  1199.976
2018-11-03 CA-2018-100622    DK-13090                      Canon Image Class D660 Copier   959.984
2018-11-16 CA-2018-160633    BS-11380 Hewlett Packard 610 Color Digital Copier / Printer   899.982
2018-11-17 CA-2018-166709    HL-15040              Canon imageCLASS 2200 Advanced Copier 10499.970

In [ ]:

november_copier_sales_increase = (
    november_copier_summary.loc[2018, "Total_Sales"]
    - november_copier_summary.loc[2017, "Total_Sales"]
)

canon_2200_sales = november_copiers.loc[
    november_copiers["Product Name"] ==
    "Canon imageCLASS 2200 Advanced Copier",
    "Sales"
].sum()

canon_contribution_pct = (
    canon_2200_sales / november_copier_sales_increase
) * 100

print("November Copier Sales increase:", round(november_copier_sales_increase, 2))
print("Canon imageCLASS 2200 Sales:", round(canon_2200_sales, 2))
print("Canon contribution to increase (%):", round(canon_contribution_pct, 2))

November Copier Sales increase: 11159.96
Canon imageCLASS 2200 Sales: 10499.97
Canon contribution to increase (%): 94.09

In [ ]:

november_copier_sales_2018 = november_copier_summary.loc[2018, "Total_Sales"]
november_copier_sales_2017 = november_copier_summary.loc[2017, "Total_Sales"]

sales_2018_without_canon = (
    november_copier_sales_2018 - canon_2200_sales
)

change_without_canon = (
    sales_2018_without_canon - november_copier_sales_2017
)

print("2017 November Copier Sales:", round(november_copier_sales_2017, 2))
print("2018 Sales without Canon transaction:", round(sales_2018_without_canon, 2))
print("Change without Canon transaction:", round(change_without_canon, 2))

2017 November Copier Sales: 1199.98
2018 Sales without Canon transaction: 1859.97
Change without Canon transaction: 659.99

In [ ]:

growth_with_canon = (
    (november_copier_sales_2018 - november_copier_sales_2017)
    / november_copier_sales_2017
) * 100

growth_without_canon = (
    (sales_2018_without_canon - november_copier_sales_2017)
    / november_copier_sales_2017
) * 100

canon_sensitivity_summary = pd.DataFrame({
    "Scenario": [
        "Reported 2018 Sales",
        "2018 Sales without Canon transaction"
    ],
    "Sales": [
        november_copier_sales_2018,
        sales_2018_without_canon
    ],
    "Growth_vs_2017_Pct": [
        growth_with_canon,
        growth_without_canon
    ]
})

print(canon_sensitivity_summary.round(2).to_string(index=False))

                            Scenario    Sales  Growth_vs_2017_Pct
                 Reported 2018 Sales 12359.94              930.02
2018 Sales without Canon transaction  1859.97               55.00

In [ ]:

november_copier_findings = pd.DataFrame({
    "Metric": [
        "November 2017 Copier Sales",
        "November 2018 Copier Sales",
        "Reported Sales increase",
        "Reported growth (%)",
        "Canon transaction Sales",
        "Canon contribution to increase (%)",
        "2018 Sales without Canon",
        "Growth without Canon (%)"
    ],
    "Value": [
        november_copier_sales_2017,
        november_copier_sales_2018,
        november_copier_sales_2018 - november_copier_sales_2017,
        growth_with_canon,
        canon_2200_sales,
        canon_contribution_pct,
        sales_2018_without_canon,
        growth_without_canon
    ]
})

print(november_copier_findings.round(2).to_string(index=False))

                            Metric    Value
        November 2017 Copier Sales  1199.98
        November 2018 Copier Sales 12359.94
           Reported Sales increase 11159.96
               Reported growth (%)   930.02
           Canon transaction Sales 10499.97
Canon contribution to increase (%)    94.09
          2018 Sales without Canon  1859.97
          Growth without Canon (%)    55.00

In [ ]:

november_all_subcategories = df[
    (df["Order Date"].dt.month == 11) &
    (df["Order Date"].dt.year.isin([2017, 2018]))
]

november_subcategory_summary = november_all_subcategories.pivot_table(
    index=["Category", "Sub-Category"],
    columns=november_all_subcategories["Order Date"].dt.year,
    values="Sales",
    aggfunc="sum",
    fill_value=0
)

november_subcategory_summary["Sales_Change"] = (
    november_subcategory_summary[2018]
    - november_subcategory_summary[2017]
)

print(
    november_subcategory_summary
    .sort_values("Sales_Change", ascending=False)
    .round(2)
)

Order Date                        2017      2018  Sales_Change
Category        Sub-Category
Technology      Copiers        1199.98  12359.94      11159.96
                Phones         9103.07  17201.04       8097.97
Furniture       Tables         8778.49  13658.69       4880.20
Office Supplies Storage        7057.63  11911.28       4853.64
                Appliances     2978.06   6746.07       3768.01
Technology      Machines       8756.64  11761.38       3004.74
Furniture       Furnishings    4034.78   6714.12       2679.34
Office Supplies Binders        4849.45   6490.56       1641.12
                Paper          2097.91   3620.61       1522.71
Furniture       Chairs        13173.08  14561.22       1388.14
Office Supplies Art             892.07   1387.04        494.97
                Supplies        356.03    452.00         95.97
Technology      Accessories    8081.38   8086.75          5.37
Office Supplies Fasteners       192.41    138.21        -54.20
                Envelopes       807.56    518.63       -288.93
                Labels          910.69    207.93       -702.76
Furniture       Bookcases      5797.27   2122.69      -3674.59

In [ ]:

subcategory_total_change = (
    november_subcategory_summary["Sales_Change"].sum()
)

november_total_sales = november_all_subcategories.groupby(
    november_all_subcategories["Order Date"].dt.year
)["Sales"].sum()

november_overall_change = (
    november_total_sales.loc[2018] - november_total_sales.loc[2017]
)

print("Sum of subcategory changes:", round(subcategory_total_change, 2))
print("Overall November Sales increase:", round(november_overall_change, 2))
print(
    "Difference:",
    round(subcategory_total_change - november_overall_change, 2)
)

Sum of subcategory changes: 38871.66
Overall November Sales increase: 38871.66
Difference: 0.0

In [ ]:

november_subcategory_summary["Contribution_%"] = (
    november_subcategory_summary["Sales_Change"]
    / november_overall_change
) * 100

print(
    november_subcategory_summary[
        ["Sales_Change", "Contribution_%"]
    ]
    .sort_values("Contribution_%", ascending=False)
    .round(2)
)

Order Date                    Sales_Change  Contribution_%
Category        Sub-Category
Technology      Copiers           11159.96           28.71
                Phones             8097.97           20.83
Furniture       Tables             4880.20           12.55
Office Supplies Storage            4853.64           12.49
                Appliances         3768.01            9.69
Technology      Machines           3004.74            7.73
Furniture       Furnishings        2679.34            6.89
Office Supplies Binders            1641.12            4.22
                Paper              1522.71            3.92
Furniture       Chairs             1388.14            3.57
Office Supplies Art                 494.97            1.27
                Supplies             95.97            0.25
Technology      Accessories           5.37            0.01
Office Supplies Fasteners           -54.20           -0.14
                Envelopes          -288.93           -0.74
                Labels             -702.76           -1.81
Furniture       Bookcases         -3674.59           -9.45

In [ ]:

total_contribution = november_subcategory_summary[
    "Contribution_%"
].sum()

print("Total contribution:", round(total_contribution, 2), "%")

Total contribution: 100.0 %

In [ ]:

monthly_growth_summary = pd.DataFrame({
    "Sales_Change": monthly_sales_change,
    "Contribution_%": monthly_contribution
})

print(
    monthly_growth_summary
    .sort_values("Sales_Change", ascending=False)
    .round(2)
)

NameError: name 'monthly_contribution' is not defined

In [ ]:

# Calculate monthly Sales change: 2018 minus 2017
monthly_sales_change = (
    monthly_sales_by_year[2018]
    - monthly_sales_by_year[2017]
)

# Calculate each month's contribution to the net annual increase
monthly_contribution = (
    monthly_sales_change
    / monthly_sales_change.sum()
) * 100

# Combine both results into one summary table
monthly_growth_summary = pd.DataFrame({
    "Sales_Change": monthly_sales_change,
    "Contribution_%": monthly_contribution
})

print(
    monthly_growth_summary
    .sort_values("Sales_Change", ascending=False)
    .round(2)
)

            Sales_Change  Contribution_%
Order Date
11              38871.66           31.90
8               32295.65           26.50
1               24933.98           20.46
10              17865.10           14.66
9               16959.50           13.92
6                8466.24            6.95
3                7698.35            6.32
7                6504.32            5.34
2               -3057.82           -2.51
4               -3137.86           -2.57
12             -12708.73          -10.43
5              -12830.93          -10.53

In [ ]:

print(
    "Total monthly contribution:",
    round(monthly_growth_summary["Contribution_%"].sum(), 2),
    "%"
)

print(
    "Total monthly Sales change:",
    round(monthly_growth_summary["Sales_Change"].sum(), 2)
)

Total monthly contribution: 100.0 %
Total monthly Sales change: 121859.47

In [ ]:

from google.colab import files

uploaded = files.upload()

Saving train.csv to train.csv

In [ ]:

import pandas as pd

df = pd.read_csv("train.csv")

df["Order Date"] = pd.to_datetime(
    df["Order Date"],
    format="%d-%m-%Y"
)

df["Ship Date"] = pd.to_datetime(
    df["Ship Date"],
    format="%d-%m-%Y"
)

df["Ship Days"] = (
    df["Ship Date"] - df["Order Date"]
).dt.days

print("Dataset shape:", df.shape)

Dataset shape: (9800, 19)

In [ ]:

print("Dataset shape:", df.shape)

print("\nColumn names:")
print(df.columns.tolist())

print("\nOrder Date data type:")
print(df["Order Date"].dtype)

print("\nShip Days available:", "Ship Days" in df.columns)

Dataset shape: (9800, 19)

Column names:
['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State', 'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name', 'Sales', 'Ship Days']

Order Date data type:
datetime64[ns]

Ship Days available: True

In [ ]:

# Extract the year from each order date
df["Order Year"] = df["Order Date"].dt.year

# Calculate total Sales for each year
annual_sales = df.groupby("Order Year")["Sales"].sum()

# Calculate year-over-year Sales growth
annual_growth = annual_sales.pct_change() * 100

# Combine the results
annual_sales_summary = pd.DataFrame({
    "Total Sales": annual_sales,
    "YoY Growth %": annual_growth
})

print(annual_sales_summary.round(2))

            Total Sales  YoY Growth %
Order Year
2015          479856.21           NaN
2016          459436.01         -4.26
2017          600192.55         30.64
2018          722052.02         20.30

In [ ]:

annual_sales_change = annual_sales.diff()

annual_sales_summary["Sales Change"] = annual_sales_change

print(annual_sales_summary.round(2))

            Total Sales  YoY Growth %  Sales Change
Order Year
2015          479856.21           NaN           NaN
2016          459436.01         -4.26     -20420.20
2017          600192.55         30.64     140756.54
2018          722052.02         20.30     121859.47

In [ ]:

total_change_from_years = (
    annual_sales.iloc[-1] - annual_sales.iloc[0]
)

sum_of_annual_changes = annual_sales_change.iloc[1:].sum()

print(
    "2015 to 2018 Sales change:",
    round(total_change_from_years, 2)
)

print(
    "Sum of annual Sales changes:",
    round(sum_of_annual_changes, 2)
)

print(
    "Difference:",
    round(total_change_from_years - sum_of_annual_changes, 2)
)

2015 to 2018 Sales change: 242195.81
Sum of annual Sales changes: 242195.81
Difference: 0.0

In [ ]:

starting_sales = annual_sales.iloc[0]
ending_sales = annual_sales.iloc[-1]

overall_growth_pct = (
    (ending_sales - starting_sales)
    / starting_sales
) * 100

print("Starting Sales (2015):", round(starting_sales, 2))
print("Ending Sales (2018):", round(ending_sales, 2))
print("Total Sales increase:", round(ending_sales - starting_sales, 2))
print("Overall Sales growth:", round(overall_growth_pct, 2), "%")

Starting Sales (2015): 479856.21
Ending Sales (2018): 722052.02
Total Sales increase: 242195.81
Overall Sales growth: 50.47 %

In [ ]:

number_of_years = annual_sales.index[-1] - annual_sales.index[0]

cagr = (
    (ending_sales / starting_sales) ** (1 / number_of_years) - 1
) * 100

print("Number of years:", number_of_years)
print("Sales CAGR:", round(cagr, 2), "%")

Number of years: 3
Sales CAGR: 14.59 %

In [ ]:

annual_sales_summary["CAGR Benchmark %"] = cagr

print(
    annual_sales_summary[
        ["Total Sales", "YoY Growth %", "CAGR Benchmark %"]
    ].round(2)
)

            Total Sales  YoY Growth %  CAGR Benchmark %
Order Year
2015          479856.21           NaN             14.59
2016          459436.01         -4.26             14.59
2017          600192.55         30.64             14.59
2018          722052.02         20.30             14.59

In [ ]:

annual_sales_summary["Growth Rate Change (pp)"] = (
    annual_sales_summary["YoY Growth %"].diff()
)

print(
    annual_sales_summary[
        ["YoY Growth %", "Growth Rate Change (pp)"]
    ].round(2)
)

            YoY Growth %  Growth Rate Change (pp)
Order Year
2015                 NaN                      NaN
2016               -4.26                      NaN
2017               30.64                    34.89
2018               20.30                   -10.33

In [ ]:

annual_business_summary = annual_sales_summary[
    [
        "Total Sales",
        "Sales Change",
        "YoY Growth %",
        "Growth Rate Change (pp)"
    ]
].copy()

print(annual_business_summary.round(2))

            Total Sales  Sales Change  YoY Growth %  Growth Rate Change (pp)
Order Year
2015          479856.21           NaN           NaN                      NaN
2016          459436.01     -20420.20         -4.26                      NaN
2017          600192.55     140756.54         30.64                    34.89
2018          722052.02     121859.47         20.30                   -10.33

In [ ]:

print(
    "Years included:",
    annual_business_summary.index.tolist()
)

print(
    "\nSales totals match:",
    annual_business_summary["Total Sales"].equals(annual_sales)
)

print(
    "Number of annual records:",
    len(annual_business_summary)
)

Years included: [2015, 2016, 2017, 2018]

Sales totals match: True
Number of annual records: 4

In [ ]:

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9800 non-null   int64
 1   Order ID       9800 non-null   object
 2   Order Date     9800 non-null   datetime64[ns]
 3   Ship Date      9800 non-null   datetime64[ns]
 4   Ship Mode      9800 non-null   object
 5   Customer ID    9800 non-null   object
 6   Customer Name  9800 non-null   object
 7   Segment        9800 non-null   object
 8   Country        9800 non-null   object
 9   City           9800 non-null   object
 10  State          9800 non-null   object
 11  Postal Code    9789 non-null   float64
 12  Region         9800 non-null   object
 13  Product ID     9800 non-null   object
 14  Category       9800 non-null   object
 15  Sub-Category   9800 non-null   object
 16  Product Name   9800 non-null   object
 17  Sales          9800 non-null   float64
 18  Ship Days      9800 non-null   int64
 19  Order Year     9800 non-null   int32
dtypes: datetime64[ns](2), float64(2), int32(1), int64(2), object(13)
memory usage: 1.5+ MB

In [ ]:

missing_values = df.isnull().sum()

missing_summary = missing_values[missing_values > 0]

print("Columns with missing values:")
print(missing_summary)

print("\nTotal missing cells:", int(missing_values.sum()))

Columns with missing values:
Postal Code    11
dtype: int64

Total missing cells: 11

In [ ]:

sql_type_mapping = pd.DataFrame({
    "Pandas Type": df.dtypes.astype(str)
})

print(sql_type_mapping)

                  Pandas Type
Row ID                  int64
Order ID               object
Order Date     datetime64[ns]
Ship Date      datetime64[ns]
Ship Mode              object
Customer ID            object
Customer Name          object
Segment                object
Country                object
City                   object
State                  object
Postal Code           float64
Region                 object
Product ID             object
Category               object
Sub-Category           object
Product Name           object
Sales                 float64
Ship Days               int64
Order Year              int32

In [ ]:

import sqlite3

connection = sqlite3.connect(":memory:")

print("SQLite connection successful")

connection.close()

SQLite connection successful

In [ ]:

create_table_sql = """
CREATE TABLE sales (
    "Row ID" INTEGER,
    "Order ID" TEXT,
    "Order Date" TEXT,
    "Ship Date" TEXT,
    "Ship Mode" TEXT,
    "Customer ID" TEXT,
    "Customer Name" TEXT,
    "Segment" TEXT,
    "Country" TEXT,
    "City" TEXT,
    "State" TEXT,
    "Postal Code" TEXT,
    "Region" TEXT,
    "Product ID" TEXT,
    "Category" TEXT,
    "Sub-Category" TEXT,
    "Product Name" TEXT,
    "Sales" REAL,
    "Ship Days" INTEGER,
    "Order Year" INTEGER
);
"""

connection.execute(create_table_sql)

print("SQLite sales table created successfully")

ProgrammingError: Cannot operate on a closed database.

In [ ]:

import sqlite3

# Open a fresh in-memory database connection
connection = sqlite3.connect(":memory:")

# Create the sales table
create_table_sql = """
CREATE TABLE sales (
    "Row ID" INTEGER,
    "Order ID" TEXT,
    "Order Date" TEXT,
    "Ship Date" TEXT,
    "Ship Mode" TEXT,
    "Customer ID" TEXT,
    "Customer Name" TEXT,
    "Segment" TEXT,
    "Country" TEXT,
    "City" TEXT,
    "State" TEXT,
    "Postal Code" TEXT,
    "Region" TEXT,
    "Product ID" TEXT,
    "Category" TEXT,
    "Sub-Category" TEXT,
    "Product Name" TEXT,
    "Sales" REAL,
    "Ship Days" INTEGER,
    "Order Year" INTEGER
);
"""

connection.execute(create_table_sql)

print("SQLite sales table created successfully")

SQLite sales table created successfully